<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 General Statistics | Statistical Computing</title>
  <meta name="description" content="Chapter 4 General Statistics | Statistical Computing" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 General Statistics | Statistical Computing" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 General Statistics | Statistical Computing" />
  
  
  

<meta name="author" content="YOUR NAME HERE" />


<meta name="date" content="2024-11-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="group-manipulation.html"/>
<link rel="next" href="simple-linear-regression.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">SHORT TITLE HERE</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Reviews</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#data-types-and-structures"><i class="fa fa-check"></i><b>1.1</b> Data Types and Structures</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#data-types"><i class="fa fa-check"></i><b>1.1.1</b> Data Types</a></li>
<li class="chapter" data-level="1.1.2" data-path="index.html"><a href="index.html#data-structures"><i class="fa fa-check"></i><b>1.1.2</b> Data Structures</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#data-importing-and-exporting"><i class="fa fa-check"></i><b>1.2</b> Data Importing and Exporting</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#data-cleaning"><i class="fa fa-check"></i><b>1.3</b> Data Cleaning</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#data-visualization"><i class="fa fa-check"></i><b>1.4</b> Data Visualization</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#hands-on-exercises"><i class="fa fa-check"></i><b>1.5</b> <span style="color: green;"><strong>Hands-on Exercises</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>2</b> Functions</a>
<ul>
<li class="chapter" data-level="2.1" data-path="functions.html"><a href="functions.html#writing-functions"><i class="fa fa-check"></i><b>2.1</b> Writing Functions</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="functions.html"><a href="functions.html#user-defined-functions"><i class="fa fa-check"></i><b>2.1.1</b> User-Defined Functions</a></li>
<li class="chapter" data-level="2.1.2" data-path="functions.html"><a href="functions.html#built-in-fuctions"><i class="fa fa-check"></i><b>2.1.2</b> Built-in Fuctions</a></li>
<li class="chapter" data-level="2.1.3" data-path="functions.html"><a href="functions.html#package-functions"><i class="fa fa-check"></i><b>2.1.3</b> Package Functions</a></li>
<li class="chapter" data-level="2.1.4" data-path="functions.html"><a href="functions.html#type-of-arguments-in-r-functions"><i class="fa fa-check"></i><b>2.1.4</b> Type of arguments in R functions</a></li>
<li class="chapter" data-level="2.1.5" data-path="functions.html"><a href="functions.html#understanding-return-values-in-r-functions"><i class="fa fa-check"></i><b>2.1.5</b> Understanding Return Values in R Functions</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="functions.html"><a href="functions.html#calling-the-functions"><i class="fa fa-check"></i><b>2.2</b> Calling the Functions</a></li>
<li class="chapter" data-level="2.3" data-path="functions.html"><a href="functions.html#function-documentation"><i class="fa fa-check"></i><b>2.3</b> Function Documentation</a></li>
<li class="chapter" data-level="2.4" data-path="functions.html"><a href="functions.html#hands-on-exercise"><i class="fa fa-check"></i><b>2.4</b> <span style="color: green;"><strong>Hands-on Exercise</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="group-manipulation.html"><a href="group-manipulation.html"><i class="fa fa-check"></i><b>3</b> Group Manipulation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="group-manipulation.html"><a href="group-manipulation.html#apply-family"><i class="fa fa-check"></i><b>3.1</b> Apply Family</a></li>
<li class="chapter" data-level="3.2" data-path="group-manipulation.html"><a href="group-manipulation.html#aggregate-plyr"><i class="fa fa-check"></i><b>3.2</b> Aggregate Plyr</a></li>
<li class="chapter" data-level="3.3" data-path="group-manipulation.html"><a href="group-manipulation.html#data-reshaping"><i class="fa fa-check"></i><b>3.3</b> Data Reshaping</a></li>
<li class="chapter" data-level="3.4" data-path="group-manipulation.html"><a href="group-manipulation.html#hands-on-exercise-1"><i class="fa fa-check"></i><b>3.4</b> <span style="color: green;"><strong>Hands-on Exercise</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="general-statistics.html"><a href="general-statistics.html"><i class="fa fa-check"></i><b>4</b> General Statistics</a>
<ul>
<li class="chapter" data-level="4.1" data-path="general-statistics.html"><a href="general-statistics.html#measure-of-spread-and-central-tendency"><i class="fa fa-check"></i><b>4.1</b> Measure of Spread and Central Tendency</a></li>
<li class="chapter" data-level="4.2" data-path="general-statistics.html"><a href="general-statistics.html#data-visualization-1"><i class="fa fa-check"></i><b>4.2</b> Data Visualization</a></li>
<li class="chapter" data-level="4.3" data-path="general-statistics.html"><a href="general-statistics.html#inferential-statistics"><i class="fa fa-check"></i><b>4.3</b> Inferential Statistics</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="general-statistics.html"><a href="general-statistics.html#introduction-to-hypothesis-testing"><i class="fa fa-check"></i><b>4.3.1</b> Introduction to Hypothesis Testing</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="general-statistics.html"><a href="general-statistics.html#hands-on-exercise-2"><i class="fa fa-check"></i><b>4.4</b> <span style="color: green;"><strong>Hands-on Exercise</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html"><i class="fa fa-check"></i><b>5</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="5.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#basics-of-wilkinson-rogers-notation-y-x-linear-regression"><i class="fa fa-check"></i><b>5.1</b> Basics of Wilkinson-Rogers Notation (y ~ x), Linear Regression</a></li>
<li class="chapter" data-level="5.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#scatterplots-with-regression-lines-reading-lm-output"><i class="fa fa-check"></i><b>5.2</b> Scatterplots with Regression Lines, Reading lm() Output</a></li>
<li class="chapter" data-level="5.3" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#confidence-intervals-for-regression-coefficients-testing-coefficients"><i class="fa fa-check"></i><b>5.3</b> Confidence Intervals for Regression Coefficients, Testing Coefficients</a></li>
<li class="chapter" data-level="5.4" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#identifying-points-in-a-plot"><i class="fa fa-check"></i><b>5.4</b> Identifying Points in a Plot</a></li>
<li class="chapter" data-level="5.5" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#hands-on-exercise-3"><i class="fa fa-check"></i><b>5.5</b> <span style="color: green;"><strong>Hands-On Exercise</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="reproducibility-and-report-with-r-markdown.html"><a href="reproducibility-and-report-with-r-markdown.html"><i class="fa fa-check"></i><b>6</b> Reproducibility and Report with R Markdown</a>
<ul>
<li class="chapter" data-level="6.1" data-path="reproducibility-and-report-with-r-markdown.html"><a href="reproducibility-and-report-with-r-markdown.html#key-tools-in-r-for-reproducibility-and-reporting"><i class="fa fa-check"></i><b>6.1</b> Key Tools in R for Reproducibility and Reporting</a></li>
<li class="chapter" data-level="6.2" data-path="reproducibility-and-report-with-r-markdown.html"><a href="reproducibility-and-report-with-r-markdown.html#creating-reproducible-reports"><i class="fa fa-check"></i><b>6.2</b> Creating Reproducible Reports</a></li>
<li class="chapter" data-level="6.3" data-path="reproducibility-and-report-with-r-markdown.html"><a href="reproducibility-and-report-with-r-markdown.html#going-beyond-shiny-for-interactive-reporting"><i class="fa fa-check"></i><b>6.3</b> Going Beyond: Shiny for Interactive Reporting</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="r-shiny.html"><a href="r-shiny.html"><i class="fa fa-check"></i><b>7</b> R Shiny</a>
<ul>
<li class="chapter" data-level="7.1" data-path="r-shiny.html"><a href="r-shiny.html#structure-of-a-shiny-app"><i class="fa fa-check"></i><b>7.1</b> Structure of a Shiny App</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="r-shiny.html"><a href="r-shiny.html#user-interfaceui"><i class="fa fa-check"></i><b>7.1.1</b> User Interface(ui)</a></li>
<li class="chapter" data-level="7.1.2" data-path="r-shiny.html"><a href="r-shiny.html#server"><i class="fa fa-check"></i><b>7.1.2</b> Server</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="r-shiny.html"><a href="r-shiny.html#hands-on-exercise-4"><i class="fa fa-check"></i><b>7.2</b> <span style="color: green;"><strong>Hands-On Exercise</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="building-r-packages.html"><a href="building-r-packages.html"><i class="fa fa-check"></i><b>8</b> Building R Packages</a>
<ul>
<li class="chapter" data-level="8.1" data-path="building-r-packages.html"><a href="building-r-packages.html#introduction"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="building-r-packages.html"><a href="building-r-packages.html#prerequisites"><i class="fa fa-check"></i><b>8.2</b> Prerequisites</a></li>
<li class="chapter" data-level="8.3" data-path="building-r-packages.html"><a href="building-r-packages.html#building-a-simple-r-package"><i class="fa fa-check"></i><b>8.3</b> Building a simple R package</a></li>
<li class="chapter" data-level="8.4" data-path="building-r-packages.html"><a href="building-r-packages.html#making-a-new-r-project"><i class="fa fa-check"></i><b>8.4</b> Making A New R Project</a></li>
<li class="chapter" data-level="8.5" data-path="building-r-packages.html"><a href="building-r-packages.html#adding-documentation"><i class="fa fa-check"></i><b>8.5</b> Adding Documentation</a></li>
<li class="chapter" data-level="8.6" data-path="building-r-packages.html"><a href="building-r-packages.html#uploading-and-installing-from-github"><i class="fa fa-check"></i><b>8.6</b> Uploading and Installing from Github</a></li>
<li class="chapter" data-level="8.7" data-path="building-r-packages.html"><a href="building-r-packages.html#hands-on-exercises-1"><i class="fa fa-check"></i><b>8.7</b> <span style="color: green;"><strong>Hands-on Exercises</strong></span></a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Computing</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="general-statistics" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> General Statistics<a href="general-statistics.html#general-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this course, we will require the ecommerce data set that can be downloaded from <a href="https://www.kaggle.com/datasets/shrishtimanja/ecommerce-dataset-for-data-analysis/data">here</a>.</p>
<p>Lets load the data set</p>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb286-1"><a href="general-statistics.html#cb286-1" tabindex="-1"></a>ecommerce <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/ecommerce.csv&quot;</span>)</span>
<span id="cb286-2"><a href="general-statistics.html#cb286-2" tabindex="-1"></a></span>
<span id="cb286-3"><a href="general-statistics.html#cb286-3" tabindex="-1"></a><span class="co"># First few rows of the data set </span></span>
<span id="cb286-4"><a href="general-statistics.html#cb286-4" tabindex="-1"></a><span class="fu">head</span>(ecommerce)</span></code></pre></div>
<pre><code>##      CID        TID Gender    Age.Group       Purchase.Date Product.Category
## 1 943146 5876328741 Female        25-45 30/08/2023 20:27:08      Electronics
## 2 180079 1018503182   Male        25-45 23/02/2024 09:33:46      Electronics
## 3 337580 3814082218  Other 60 and above 06/03/2022 09:09:50         Clothing
## 4 180333 1395204173  Other 60 and above 04/11/2020 04:41:57 Sports &amp; Fitness
## 5 447553 8009390577   Male        18-25 31/05/2022 17:00:32 Sports &amp; Fitness
## 6 200614 3994452858   Male        18-25 12/07/2021 15:10:27         Clothing
##   Discount.Availed   Discount.Name Discount.Amount..INR. Gross.Amount
## 1              Yes       FESTIVE50                 64.30      725.304
## 2              Yes SEASONALOFFER21                175.19     4638.992
## 3              Yes SEASONALOFFER21                211.54     1986.373
## 4               No                                  0.00     5695.613
## 5              Yes        WELCOME5                439.92     2292.651
## 6              Yes       FESTIVE50                127.01     3649.397
##   Net.Amount Purchase.Method  Location
## 1    661.004     Credit Card Ahmedabad
## 2   4463.802     Credit Card Bangalore
## 3   1774.833     Credit Card     Delhi
## 4   5695.613      Debit Card     Delhi
## 5   1852.731     Credit Card     Delhi
## 6   3522.387     Credit Card     Delhi</code></pre>
<p>We will explore the fundamentals of statistics using the data set that is packed with real-life insights on customers and their purchasing behavior. At the end of this course unit you will be able to understand;</p>
<ul>
<li>Measure of spread and central tendency
<ul>
<li>Mean(the average)</li>
<li>Mode</li>
<li>Quartiles</li>
<li>Range(IQR, maximum and minimum)</li>
<li>Standard deviation and variance</li>
</ul></li>
<li>Data Visualizations
<ul>
<li>Relationship(scatter plot and heatmaps)</li>
<li>Trend(line chart)</li>
<li>Distribution(histograms and density plots)</li>
<li>Comparison(bar charts)</li>
<li>Composition (pie charts)</li>
<li>Outliers (boxplots and violin plots)</li>
</ul></li>
<li>Inferential Statistics
<ul>
<li>Hypothesis testing</li>
<li>T-tests( one sample, anova, chi-square)</li>
</ul></li>
</ul>
<div id="measure-of-spread-and-central-tendency" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Measure of Spread and Central Tendency<a href="general-statistics.html#measure-of-spread-and-central-tendency" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Central tendency identifies the center or typical value of a data set. Measuring central tendency summarizes the data by identifying skewness, distribution and how the data is robust to outliers. Business calculate the central tendencies like average sales, median customer age to make informed decision-making.</p>
<p>Here are some of the statistical concepts used to define central tendecy and spread;</p>
<ol style="list-style-type: lower-alpha">
<li>Mean</li>
<li>Mode</li>
<li>Quartiles(Median, upper and lower quartile)</li>
<li>Range and IQR</li>
<li>Variance and standard deviation</li>
</ol>
<p>a.<strong>Arithmetic mean</strong></p>
<p>It is also referred to as the average. It is the sum of all values divided by the number of values in the set. R has a function <code>mean</code> to calculate the average.</p>
<p>Here is the formula for mean; <span class="math display">\[\overline{x} ={ \sum^{n}_{i=1}x_i\over{n}}\]</span></p>
<p>Where;</p>
<ul>
<li><span class="math inline">\(\overline{x}\)</span> is the mean</li>
<li><span class="math inline">\(x_i\)</span> represent value at position <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(n\)</span> is the number(count) of values in a set</li>
</ul>
<p>Lets calculate the average net amount spent on the ecommerce store.</p>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb288-1"><a href="general-statistics.html#cb288-1" tabindex="-1"></a><span class="co"># Calculate the mean net amount</span></span>
<span id="cb288-2"><a href="general-statistics.html#cb288-2" tabindex="-1"></a><span class="fu">mean</span>(ecommerce<span class="sc">$</span>Net.Amount)</span></code></pre></div>
<pre><code>## [1] 2875.95</code></pre>
<p>The average amount spent on the e-commerce store by all the customers was 2875.95 INR.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li><strong>Mode</strong></li>
</ol>
<p>The mode shows the most frequent value, thereby pinpoint the most popular categories in a data set. In the commerce data set we will find the most popular category and age group in the data set.</p>
<p>Find the most popular category</p>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb290-1"><a href="general-statistics.html#cb290-1" tabindex="-1"></a><span class="co"># Calculate the mode for &#39;ProductCategory&#39;</span></span>
<span id="cb290-2"><a href="general-statistics.html#cb290-2" tabindex="-1"></a><span class="fu">table</span>(ecommerce<span class="sc">$</span>Product.Category)</span></code></pre></div>
<pre><code>## 
## Beauty and Health             Books          Clothing       Electronics 
##              8332              2762             10968             16574 
##    Home &amp; Kitchen             Other          Pet Care  Sports &amp; Fitness 
##              5489              2171              1618              5557 
##      Toys &amp; Games 
##              1529</code></pre>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb292-1"><a href="general-statistics.html#cb292-1" tabindex="-1"></a><span class="fu">which.max</span>(<span class="fu">table</span>(ecommerce<span class="sc">$</span>Product.Category))</span></code></pre></div>
<pre><code>## Electronics 
##           4</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li><strong>Quartiles</strong></li>
</ol>
<p>These are values that divide a data set into four equal parts, each representing the 25% of the data points. They help describe the spread of the data, providing insights into the distribution’s shape and spread.</p>
<p>The quartiles are;</p>
<ol style="list-style-type: lower-roman">
<li><em>First Quartile(Q1)</em> - The <span class="math inline">\(25^{th}\)</span> percentile; the value below which 25% of the data falls. Also known as the lower quartile.</li>
<li><em>Median(Q2)</em> - Also known as the second quartile; the middle of the data set, where half of the values are above and another half of the values are below.</li>
<li><em>Third quartile(Q3)</em> - The <span class="math inline">\(75^{th}\)</span> percentile; the value below which 75% of the data falls.</li>
</ol>
<p>Using quartiles, we can calculate the <strong>Interquartile Range (IQR)</strong>, which measures the spread of the middle 50% of the data. <span class="math display">\[IQR = Q3 - Q1\]</span></p>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>Lets put this into action; we will create a vector ages and calculate the quartiles.</p>
<p><code>ages &lt;- c(21, 27, 55, 13, 87, 51, 33, 64, 40)</code></p>
<p>Lets line the ages in an ascending order</p>
<p><code>ages &lt;- c(13, 21, 27, 33, 40, 51, 55, 64, 87)</code></p>
<p>Finding the;
- median, will be middle value which is <code>40</code>.
- Q1, is the median of the lower half which is</p>
<pre><code>Q1  = (21 + 27)/2 = 24</code></pre>
<ul>
<li>Q3, is the median of the upper half which is</li>
</ul>
<pre><code>Q3 = (55 + 64)/2 = 59.5</code></pre>
<p>Using R to calculate quartiles using the <code>quantile()</code> function;</p>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb296-1"><a href="general-statistics.html#cb296-1" tabindex="-1"></a>ages <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">21</span>, <span class="dv">27</span>, <span class="dv">55</span>, <span class="dv">13</span>, <span class="dv">87</span>, <span class="dv">51</span>, <span class="dv">33</span>, <span class="dv">64</span>, <span class="dv">40</span>)</span>
<span id="cb296-2"><a href="general-statistics.html#cb296-2" tabindex="-1"></a></span>
<span id="cb296-3"><a href="general-statistics.html#cb296-3" tabindex="-1"></a><span class="co"># Calculate the quartiles </span></span>
<span id="cb296-4"><a href="general-statistics.html#cb296-4" tabindex="-1"></a><span class="fu">quantile</span>(ages, <span class="at">type=</span><span class="dv">2</span>, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>))</span></code></pre></div>
<pre><code>## 25% 50% 75% 
##  27  40  55</code></pre>
<ol start="4" style="list-style-type: lower-alpha">
<li><strong>Range</strong></li>
</ol>
<p>To understand range, we will define, maximum and maximum values. The <strong>maximum</strong> value is the largest value in a set while the <strong>minimum</strong> is the smallest value in a set. <strong>Range</strong> is the difference between the maximum(largest value) and the minimum value in a set.</p>
<p>Here is a formula for range; <span class="math display">\[Range = Max - Min\]</span></p>
<p>Lets create a vector <code>ages</code> that defines the ages of different customers on a retail stores, find the maximum and minimum ages then calculate the range.</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="general-statistics.html#cb298-1" tabindex="-1"></a><span class="co"># Create vector ages</span></span>
<span id="cb298-2"><a href="general-statistics.html#cb298-2" tabindex="-1"></a>ages <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">21</span>, <span class="dv">27</span>, <span class="dv">55</span>, <span class="dv">13</span>, <span class="dv">87</span>, <span class="dv">51</span>, <span class="dv">33</span>, <span class="dv">64</span>)</span>
<span id="cb298-3"><a href="general-statistics.html#cb298-3" tabindex="-1"></a></span>
<span id="cb298-4"><a href="general-statistics.html#cb298-4" tabindex="-1"></a><span class="co"># Find the maximum</span></span>
<span id="cb298-5"><a href="general-statistics.html#cb298-5" tabindex="-1"></a><span class="fu">max</span>(ages)</span></code></pre></div>
<pre><code>## [1] 87</code></pre>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb300-1"><a href="general-statistics.html#cb300-1" tabindex="-1"></a><span class="co"># Find the minimum </span></span>
<span id="cb300-2"><a href="general-statistics.html#cb300-2" tabindex="-1"></a><span class="fu">min</span>(ages)</span></code></pre></div>
<pre><code>## [1] 13</code></pre>
<div class="sourceCode" id="cb302"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb302-1"><a href="general-statistics.html#cb302-1" tabindex="-1"></a><span class="co"># Calculate the range </span></span>
<span id="cb302-2"><a href="general-statistics.html#cb302-2" tabindex="-1"></a><span class="fu">diff</span>(<span class="fu">range</span>(ages))</span></code></pre></div>
<pre><code>## [1] 74</code></pre>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>Now its clear what range, lets get into the real-world scenario. We will find the maximum and minimum <code>Gross.Amount</code> spent on the ecommerce store. Finally, we calculate the range of amount spent by customers(<code>Gross.Amount</code>)</p>
<div class="sourceCode" id="cb304"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb304-1"><a href="general-statistics.html#cb304-1" tabindex="-1"></a><span class="co"># Maximum amount spent by customers </span></span>
<span id="cb304-2"><a href="general-statistics.html#cb304-2" tabindex="-1"></a><span class="fu">max</span>(ecommerce<span class="sc">$</span>Gross.Amount)</span></code></pre></div>
<pre><code>## [1] 8394.826</code></pre>
<div class="sourceCode" id="cb306"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb306-1"><a href="general-statistics.html#cb306-1" tabindex="-1"></a><span class="co"># Minimum amount spent by customers</span></span>
<span id="cb306-2"><a href="general-statistics.html#cb306-2" tabindex="-1"></a><span class="fu">min</span>(ecommerce<span class="sc">$</span>Gross.Amount)</span></code></pre></div>
<pre><code>## [1] 136.4543</code></pre>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb308-1"><a href="general-statistics.html#cb308-1" tabindex="-1"></a><span class="co"># Range </span></span>
<span id="cb308-2"><a href="general-statistics.html#cb308-2" tabindex="-1"></a><span class="fu">diff</span>(<span class="fu">range</span>(ecommerce<span class="sc">$</span>Gross.Amount))</span></code></pre></div>
<pre><code>## [1] 8258.371</code></pre>
<ol start="5" style="list-style-type: lower-alpha">
<li><strong>Standard deviation and Variance</strong></li>
</ol>
<p>Variance is statistical measure of dispersion that defines how spread the data points are in a data set in relation to the mean of the data set. Standard deviation is the measure of how data is clustered around the mean. It is simply defined to as the square root of variance.</p>
<p>Here is the formula of variance; <span class="math display">\[\sigma = {\sum(x_i - \overline{x})^2 \over{n}}\]</span></p>
<p>Where;</p>
<ul>
<li><span class="math inline">\(\sigma\)</span> is the variance</li>
<li><span class="math inline">\(x_i\)</span> is the value</li>
<li><span class="math inline">\(\overline{x}\)</span> is the population mean</li>
<li><span class="math inline">\(n\)</span> is the value count</li>
</ul>
<p>Standard is simply the square root of variance, Here is the formula for standard deviation; <span class="math display">\[S = \sqrt{\sigma}\]</span> or <span class="math display">\[S = \sqrt{{\sum(x_i - \overline{x})^2 \over{n}}}\]</span></p>
<p>Where <span class="math inline">\(S\)</span> is the standard deviation.</p>
<p>Variance and standard deviation can be calculated in R environment using <code>var()</code> and <code>sd()</code> functions respectively.</p>
<p>Lets create a vector of weights of the athletes in kilograms and calculate the variance and standard deviation.</p>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb310-1"><a href="general-statistics.html#cb310-1" tabindex="-1"></a><span class="co"># Sample vector </span></span>
<span id="cb310-2"><a href="general-statistics.html#cb310-2" tabindex="-1"></a>athlete_weights <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">55</span>, <span class="dv">76</span>, <span class="dv">52</span>, <span class="dv">68</span>, <span class="dv">71</span>, <span class="dv">63</span>, <span class="dv">58</span>, <span class="dv">52</span>, <span class="dv">85</span>, <span class="dv">96</span>)</span>
<span id="cb310-3"><a href="general-statistics.html#cb310-3" tabindex="-1"></a></span>
<span id="cb310-4"><a href="general-statistics.html#cb310-4" tabindex="-1"></a><span class="co"># Calculate variance</span></span>
<span id="cb310-5"><a href="general-statistics.html#cb310-5" tabindex="-1"></a><span class="fu">var</span>(athlete_weights)</span></code></pre></div>
<pre><code>## [1] 216.7111</code></pre>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="general-statistics.html#cb312-1" tabindex="-1"></a><span class="co"># Calculate the standard deviation</span></span>
<span id="cb312-2"><a href="general-statistics.html#cb312-2" tabindex="-1"></a><span class="fu">sd</span>(athlete_weights)</span></code></pre></div>
<pre><code>## [1] 14.72111</code></pre>
<p>Lets put into real world practice and calculate variance and standard deviation of net amount spent on the ecommerce store.</p>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb314-1"><a href="general-statistics.html#cb314-1" tabindex="-1"></a><span class="co"># Variance</span></span>
<span id="cb314-2"><a href="general-statistics.html#cb314-2" tabindex="-1"></a><span class="fu">var</span>(ecommerce<span class="sc">$</span>Net.Amount)</span></code></pre></div>
<pre><code>## [1] 2979517</code></pre>
<div class="sourceCode" id="cb316"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb316-1"><a href="general-statistics.html#cb316-1" tabindex="-1"></a><span class="co"># Standard deviation</span></span>
<span id="cb316-2"><a href="general-statistics.html#cb316-2" tabindex="-1"></a><span class="fu">sd</span>(ecommerce<span class="sc">$</span>Net.Amount)</span></code></pre></div>
<pre><code>## [1] 1726.128</code></pre>
<p><span style="color: green;"><strong>Practical Exercise</strong></span></p>
<p>Using the ecommerce data set provided at the beginning of the course, calculate the following metrics for the gross amount with R;</p>
<ol style="list-style-type: decimal">
<li>Mean</li>
<li>Median and IQR</li>
<li>Maximum, minimum and range</li>
<li>Standard deviation and variance.</li>
</ol>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<ul>
<li>Read the data set</li>
</ul>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb318-1"><a href="general-statistics.html#cb318-1" tabindex="-1"></a>ecommerce <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/ecommerce.csv&quot;</span>)</span>
<span id="cb318-2"><a href="general-statistics.html#cb318-2" tabindex="-1"></a>gross_amount <span class="ot">&lt;-</span> ecommerce<span class="sc">$</span>Gross.Amount</span></code></pre></div>
<ol style="list-style-type: decimal">
<li>Mean</li>
</ol>
<div class="sourceCode" id="cb319"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb319-1"><a href="general-statistics.html#cb319-1" tabindex="-1"></a><span class="fu">mean</span>(gross_amount)</span></code></pre></div>
<pre><code>## [1] 3012.937</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Median and IQR</li>
</ol>
<div class="sourceCode" id="cb321"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb321-1"><a href="general-statistics.html#cb321-1" tabindex="-1"></a><span class="co"># Calculate the median</span></span>
<span id="cb321-2"><a href="general-statistics.html#cb321-2" tabindex="-1"></a><span class="fu">median</span>(gross_amount)</span></code></pre></div>
<pre><code>## [1] 2954.266</code></pre>
<div class="sourceCode" id="cb323"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb323-1"><a href="general-statistics.html#cb323-1" tabindex="-1"></a><span class="co"># Calculate the IQR</span></span>
<span id="cb323-2"><a href="general-statistics.html#cb323-2" tabindex="-1"></a><span class="fu">IQR</span>(gross_amount)</span></code></pre></div>
<pre><code>## [1] 2780.11</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>Maximum, minimum and range</li>
</ol>
<div class="sourceCode" id="cb325"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb325-1"><a href="general-statistics.html#cb325-1" tabindex="-1"></a><span class="co"># Minimum</span></span>
<span id="cb325-2"><a href="general-statistics.html#cb325-2" tabindex="-1"></a><span class="fu">min</span>(gross_amount)</span></code></pre></div>
<pre><code>## [1] 136.4543</code></pre>
<div class="sourceCode" id="cb327"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb327-1"><a href="general-statistics.html#cb327-1" tabindex="-1"></a><span class="co"># Maximum </span></span>
<span id="cb327-2"><a href="general-statistics.html#cb327-2" tabindex="-1"></a><span class="fu">max</span>(gross_amount)</span></code></pre></div>
<pre><code>## [1] 8394.826</code></pre>
<div class="sourceCode" id="cb329"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb329-1"><a href="general-statistics.html#cb329-1" tabindex="-1"></a><span class="co"># Range</span></span>
<span id="cb329-2"><a href="general-statistics.html#cb329-2" tabindex="-1"></a><span class="fu">diff</span>(<span class="fu">range</span>(gross_amount))</span></code></pre></div>
<pre><code>## [1] 8258.371</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>Standard deviation and variance.</li>
</ol>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb331-1"><a href="general-statistics.html#cb331-1" tabindex="-1"></a><span class="co"># Variance </span></span>
<span id="cb331-2"><a href="general-statistics.html#cb331-2" tabindex="-1"></a><span class="fu">var</span>(gross_amount)</span></code></pre></div>
<pre><code>## [1] 2953005</code></pre>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb333-1"><a href="general-statistics.html#cb333-1" tabindex="-1"></a><span class="co"># Standard deviation</span></span>
<span id="cb333-2"><a href="general-statistics.html#cb333-2" tabindex="-1"></a><span class="fu">sd</span>(gross_amount)</span></code></pre></div>
<pre><code>## [1] 1718.431</code></pre>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>
</div>
<div id="data-visualization-1" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Data Visualization<a href="general-statistics.html#data-visualization-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Data visualization is the process of using visual elements like chart, graphs or maps to represent data in a way that is easier to understand.</p>
<p>Luckily, R has a package, <code>ggplot2</code>, specifically designed to create charts and graphs. The package is said to implement the “Grammar of Graphics” that is a conceptual framework for creating graphs by Leland Wilkinson.</p>
<p>The package can be installed by;</p>
<pre><code>install.packages(&quot;ggplot2&quot;)</code></pre>
<p>and once the package is installed it is loaded by;</p>
<div class="sourceCode" id="cb336"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb336-1"><a href="general-statistics.html#cb336-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div>
<p>Lets create simple charts with the <code>ggplot2</code> package.</p>
<ol style="list-style-type: lower-alpha">
<li><strong>Scatter plots</strong></li>
</ol>
<p>Scatter plot is used to show the numerical relationship between two or more. Lets create a simple plot.</p>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb337-1"><a href="general-statistics.html#cb337-1" tabindex="-1"></a><span class="co"># Sample data</span></span>
<span id="cb337-2"><a href="general-statistics.html#cb337-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb337-3"><a href="general-statistics.html#cb337-3" tabindex="-1"></a>  <span class="at">x =</span> <span class="fu">rnorm</span>(<span class="dv">100</span>),</span>
<span id="cb337-4"><a href="general-statistics.html#cb337-4" tabindex="-1"></a>  <span class="at">y =</span> <span class="fu">rnorm</span>(<span class="dv">100</span>)</span>
<span id="cb337-5"><a href="general-statistics.html#cb337-5" tabindex="-1"></a>)</span>
<span id="cb337-6"><a href="general-statistics.html#cb337-6" tabindex="-1"></a></span>
<span id="cb337-7"><a href="general-statistics.html#cb337-7" tabindex="-1"></a><span class="co"># Creating a scatter plot</span></span>
<span id="cb337-8"><a href="general-statistics.html#cb337-8" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="co"># data</span></span>
<span id="cb337-9"><a href="general-statistics.html#cb337-9" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span> <span class="co">#aesthetics</span></span>
<span id="cb337-10"><a href="general-statistics.html#cb337-10" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="co">#geometrics</span></span>
<span id="cb337-11"><a href="general-statistics.html#cb337-11" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Scatter Plot Example&quot;</span>, <span class="at">x =</span> <span class="st">&quot;X Values&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Y Values&quot;</span>) <span class="sc">+</span></span>
<span id="cb337-12"><a href="general-statistics.html#cb337-12" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-130-1.png" width="672" /></p>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>Lets make it more interesting by exploring the real world scenario where we will visualize the relationship between Discount and the Net Amount on the ecommerce store.</p>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb338-1"><a href="general-statistics.html#cb338-1" tabindex="-1"></a><span class="co"># Creating a scatter plot</span></span>
<span id="cb338-2"><a href="general-statistics.html#cb338-2" tabindex="-1"></a><span class="fu">ggplot</span>(ecommerce[<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>, ], <span class="co"># first 100 rows of the data</span></span>
<span id="cb338-3"><a href="general-statistics.html#cb338-3" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> Net.Amount, <span class="at">y =</span> Discount.Amount..INR.)) <span class="sc">+</span> <span class="co">#aesthetics</span></span>
<span id="cb338-4"><a href="general-statistics.html#cb338-4" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="co">#geometrics</span></span>
<span id="cb338-5"><a href="general-statistics.html#cb338-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Relationship between Net Amount and the Discount&quot;</span>, </span>
<span id="cb338-6"><a href="general-statistics.html#cb338-6" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Net Amount&quot;</span>, </span>
<span id="cb338-7"><a href="general-statistics.html#cb338-7" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Discount&quot;</span>) <span class="sc">+</span></span>
<span id="cb338-8"><a href="general-statistics.html#cb338-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-131-1.png" width="672" /></p>
<p>The scatter chart above shows that there is no clear relationship between the Net Amount spent and the discount offered since at every spending(low, medium or high) had low or high discount. High spending did not necessarily guarantee low or high discount.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li><strong>Line Chart</strong></li>
</ol>
<p>Line Chart is used to show trend(Growth or fall over time). Let create a simple line chart to show this;</p>
<div class="sourceCode" id="cb339"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb339-1"><a href="general-statistics.html#cb339-1" tabindex="-1"></a><span class="co"># Sample data </span></span>
<span id="cb339-2"><a href="general-statistics.html#cb339-2" tabindex="-1"></a>dates <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;2023-10-01&quot;</span>, <span class="st">&quot;2023-10-05&quot;</span>, <span class="st">&quot;2023-10-10&quot;</span>, <span class="st">&quot;2023-10-15&quot;</span>, <span class="st">&quot;2023-10-20&quot;</span>, <span class="st">&quot;2023-10-25&quot;</span>, <span class="st">&quot;2023-10-30&quot;</span>, <span class="st">&quot;2023-11-04&quot;</span>, <span class="st">&quot;2023-11-09&quot;</span>, <span class="st">&quot;2023-11-14&quot;</span>)</span>
<span id="cb339-3"><a href="general-statistics.html#cb339-3" tabindex="-1"></a>scores <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">75</span>, <span class="dv">82</span>, <span class="dv">88</span>, <span class="dv">85</span>, <span class="dv">90</span>, <span class="dv">87</span>, <span class="dv">92</span>, <span class="dv">95</span>, <span class="dv">98</span>, <span class="dv">100</span>)</span>
<span id="cb339-4"><a href="general-statistics.html#cb339-4" tabindex="-1"></a></span>
<span id="cb339-5"><a href="general-statistics.html#cb339-5" tabindex="-1"></a><span class="co"># Create a data frame </span></span>
<span id="cb339-6"><a href="general-statistics.html#cb339-6" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb339-7"><a href="general-statistics.html#cb339-7" tabindex="-1"></a>  <span class="at">date =</span> <span class="fu">as.Date</span>(dates),</span>
<span id="cb339-8"><a href="general-statistics.html#cb339-8" tabindex="-1"></a>  <span class="at">scores =</span> scores</span>
<span id="cb339-9"><a href="general-statistics.html#cb339-9" tabindex="-1"></a>)</span>
<span id="cb339-10"><a href="general-statistics.html#cb339-10" tabindex="-1"></a></span>
<span id="cb339-11"><a href="general-statistics.html#cb339-11" tabindex="-1"></a><span class="co"># Plot a scatter plot </span></span>
<span id="cb339-12"><a href="general-statistics.html#cb339-12" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="co"># data</span></span>
<span id="cb339-13"><a href="general-statistics.html#cb339-13" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>date, <span class="at">y=</span>scores)) <span class="sc">+</span> </span>
<span id="cb339-14"><a href="general-statistics.html#cb339-14" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb339-15"><a href="general-statistics.html#cb339-15" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb339-16"><a href="general-statistics.html#cb339-16" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Scores progression from October to November&quot;</span>,</span>
<span id="cb339-17"><a href="general-statistics.html#cb339-17" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Date&quot;</span>,</span>
<span id="cb339-18"><a href="general-statistics.html#cb339-18" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Scores&quot;</span></span>
<span id="cb339-19"><a href="general-statistics.html#cb339-19" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb339-20"><a href="general-statistics.html#cb339-20" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-132-1.png" width="672" /></p>
<p>There has a been a gradual increase of scores from October to November.</p>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>Lets put this into a real world scenario. We will plot the Gross Amount spent by Customers over the years at the ecommerce store.</p>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb340-1"><a href="general-statistics.html#cb340-1" tabindex="-1"></a><span class="co"># Convert the purchase date to date type </span></span>
<span id="cb340-2"><a href="general-statistics.html#cb340-2" tabindex="-1"></a>ecommerce<span class="sc">$</span>Purchase.Date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(ecommerce<span class="sc">$</span>Purchase.Date)</span>
<span id="cb340-3"><a href="general-statistics.html#cb340-3" tabindex="-1"></a></span>
<span id="cb340-4"><a href="general-statistics.html#cb340-4" tabindex="-1"></a><span class="co"># Plot a scatter plot </span></span>
<span id="cb340-5"><a href="general-statistics.html#cb340-5" tabindex="-1"></a><span class="fu">ggplot</span>(ecommerce[<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>, ], <span class="co"># data</span></span>
<span id="cb340-6"><a href="general-statistics.html#cb340-6" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>Purchase.Date, <span class="at">y=</span>Gross.Amount)) <span class="sc">+</span> </span>
<span id="cb340-7"><a href="general-statistics.html#cb340-7" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb340-8"><a href="general-statistics.html#cb340-8" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb340-9"><a href="general-statistics.html#cb340-9" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Gross Amount spent over time&quot;</span>,</span>
<span id="cb340-10"><a href="general-statistics.html#cb340-10" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Purchase Date&quot;</span>,</span>
<span id="cb340-11"><a href="general-statistics.html#cb340-11" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Gross Amount&quot;</span></span>
<span id="cb340-12"><a href="general-statistics.html#cb340-12" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb340-13"><a href="general-statistics.html#cb340-13" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-133-1.png" width="672" /></p>
<p>There has been gradual spikes of rise and fall of the amount spent on the store.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li><strong>Histograms and Density Plots</strong></li>
</ol>
<p>Histograms and Density plots are used to show the distribution of continuous variables. Histogram is visually similar to the bar chart however it is used show frequency and distribution across a list-like data set(vectors, lists, sets, arrays, etc) that stores continuous numeric values. The count of observation within a certain range of values are displayed.</p>
<p>Lets create a vector of random 100 ages and plot the data to a histogram.</p>
<div class="sourceCode" id="cb341"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb341-1"><a href="general-statistics.html#cb341-1" tabindex="-1"></a><span class="co"># Generate random 1000 ages between 0 and 100</span></span>
<span id="cb341-2"><a href="general-statistics.html#cb341-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb341-3"><a href="general-statistics.html#cb341-3" tabindex="-1"></a>ages <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">100</span>, <span class="dv">1000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb341-4"><a href="general-statistics.html#cb341-4" tabindex="-1"></a></span>
<span id="cb341-5"><a href="general-statistics.html#cb341-5" tabindex="-1"></a><span class="co"># Create a data frame to use with ggplot</span></span>
<span id="cb341-6"><a href="general-statistics.html#cb341-6" tabindex="-1"></a>age_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Age =</span> ages)</span>
<span id="cb341-7"><a href="general-statistics.html#cb341-7" tabindex="-1"></a></span>
<span id="cb341-8"><a href="general-statistics.html#cb341-8" tabindex="-1"></a><span class="co"># PLOTTING</span></span>
<span id="cb341-9"><a href="general-statistics.html#cb341-9" tabindex="-1"></a><span class="co"># Create the histogram using ggplot</span></span>
<span id="cb341-10"><a href="general-statistics.html#cb341-10" tabindex="-1"></a><span class="fu">ggplot</span>(age_data, <span class="fu">aes</span>(<span class="at">x =</span> Age)) <span class="sc">+</span></span>
<span id="cb341-11"><a href="general-statistics.html#cb341-11" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb341-12"><a href="general-statistics.html#cb341-12" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb341-13"><a href="general-statistics.html#cb341-13" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Histogram of Randomly Generated Ages&quot;</span>, </span>
<span id="cb341-14"><a href="general-statistics.html#cb341-14" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Age&quot;</span>, </span>
<span id="cb341-15"><a href="general-statistics.html#cb341-15" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Frequency&quot;</span>) <span class="sc">+</span></span>
<span id="cb341-16"><a href="general-statistics.html#cb341-16" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-134-1.png" width="672" /></p>
<p>The bins are groups of ages ranging 5 years</p>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>Lets put his into action and plot the distribution of Discount offered on the ecommerce store</p>
<div class="sourceCode" id="cb342"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb342-1"><a href="general-statistics.html#cb342-1" tabindex="-1"></a><span class="co"># Create the histogram using ggplot</span></span>
<span id="cb342-2"><a href="general-statistics.html#cb342-2" tabindex="-1"></a><span class="fu">ggplot</span>(ecommerce, </span>
<span id="cb342-3"><a href="general-statistics.html#cb342-3" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> Discount.Amount..INR.)) <span class="sc">+</span></span>
<span id="cb342-4"><a href="general-statistics.html#cb342-4" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">10</span>, <span class="at">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb342-5"><a href="general-statistics.html#cb342-5" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb342-6"><a href="general-statistics.html#cb342-6" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Histogram of Discount offered&quot;</span>, </span>
<span id="cb342-7"><a href="general-statistics.html#cb342-7" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Discount&quot;</span>, </span>
<span id="cb342-8"><a href="general-statistics.html#cb342-8" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Frequency&quot;</span>) <span class="sc">+</span></span>
<span id="cb342-9"><a href="general-statistics.html#cb342-9" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-135-1.png" width="672" /></p>
<p>The distribution is right skewed and most of the customers in the store were offered very low discount for their purchases.</p>
<p><strong>Check it later and speak about density plots</strong></p>
<ol start="4" style="list-style-type: lower-alpha">
<li><strong>Bar Charts</strong></li>
</ol>
<p>Bar charts are used to represent both categorical and numeric data in form of rectangular bars. The length/height of each category represents its numeric value. It may corresponds to either length, count, age or any other numerical value. Bar charts are used when;-</p>
<ol style="list-style-type: lower-roman">
<li>Comparing categorical data</li>
<li>Visualizing summarized data for instance aggregated sum, average or any other summary statistics.</li>
<li>Showing frequency or count for instance representing the number of products sold per each category.</li>
<li>Ranking data. Bar charts can effectively represents ranks especially in descending/ascending order for instance ranking the life expectancy of different countries.</li>
<li>Other type of complex bar charts like stacked bar charts can be used to compare part-to-whole relationships.</li>
</ol>
<p>There are many more uses of bar charts however there are some use cases where bar charts are not preferred like when working with continuous data, scatter and line charts are more befitting. Also, bar charts are not appropriate where data has too many categories, heatmaps will do better.</p>
<p>To create a simple bar chart using <code>ggplot2</code>, we use <code>geom_bar</code> to define that its a bar chart.</p>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb343-1"><a href="general-statistics.html#cb343-1" tabindex="-1"></a><span class="co"># Sample data</span></span>
<span id="cb343-2"><a href="general-statistics.html#cb343-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb343-3"><a href="general-statistics.html#cb343-3" tabindex="-1"></a>  <span class="at">category =</span> <span class="fu">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;C&quot;</span>, <span class="st">&quot;D&quot;</span>),</span>
<span id="cb343-4"><a href="general-statistics.html#cb343-4" tabindex="-1"></a>  <span class="at">value =</span> <span class="fu">c</span>(<span class="dv">23</span>, <span class="dv">17</span>, <span class="dv">35</span>, <span class="dv">10</span>)</span>
<span id="cb343-5"><a href="general-statistics.html#cb343-5" tabindex="-1"></a>)</span>
<span id="cb343-6"><a href="general-statistics.html#cb343-6" tabindex="-1"></a></span>
<span id="cb343-7"><a href="general-statistics.html#cb343-7" tabindex="-1"></a><span class="do">## The data set above will be used to create a bar chart</span></span>
<span id="cb343-8"><a href="general-statistics.html#cb343-8" tabindex="-1"></a><span class="co"># Creating a bar chart</span></span>
<span id="cb343-9"><a href="general-statistics.html#cb343-9" tabindex="-1"></a><span class="fu">ggplot</span>(df, </span>
<span id="cb343-10"><a href="general-statistics.html#cb343-10" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> category, <span class="at">y =</span> value)) <span class="sc">+</span></span>
<span id="cb343-11"><a href="general-statistics.html#cb343-11" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="sc">+</span></span>
<span id="cb343-12"><a href="general-statistics.html#cb343-12" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb343-13"><a href="general-statistics.html#cb343-13" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Value by Category&quot;</span>, </span>
<span id="cb343-14"><a href="general-statistics.html#cb343-14" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Category&quot;</span>, </span>
<span id="cb343-15"><a href="general-statistics.html#cb343-15" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Value&quot;</span>) <span class="sc">+</span></span>
<span id="cb343-16"><a href="general-statistics.html#cb343-16" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-136-1.png" width="672" /></p>
<p>From the bar chart above, Category “C” has the largest value while category “D” has the lowest value.</p>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>Lets create a bar chart of a real world scenario. We will calculate the average Gross amount spent by different age groups in the ecommerce store.</p>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb344-1"><a href="general-statistics.html#cb344-1" tabindex="-1"></a><span class="fu">library</span>(plyr)</span>
<span id="cb344-2"><a href="general-statistics.html#cb344-2" tabindex="-1"></a></span>
<span id="cb344-3"><a href="general-statistics.html#cb344-3" tabindex="-1"></a><span class="co"># Aggregate by mean</span></span>
<span id="cb344-4"><a href="general-statistics.html#cb344-4" tabindex="-1"></a>PurchasebyAge <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(Gross.Amount <span class="sc">~</span> Age.Group,</span>
<span id="cb344-5"><a href="general-statistics.html#cb344-5" tabindex="-1"></a>                           <span class="at">data =</span> ecommerce,</span>
<span id="cb344-6"><a href="general-statistics.html#cb344-6" tabindex="-1"></a>                           <span class="at">FUN =</span> mean</span>
<span id="cb344-7"><a href="general-statistics.html#cb344-7" tabindex="-1"></a>                           )</span>
<span id="cb344-8"><a href="general-statistics.html#cb344-8" tabindex="-1"></a></span>
<span id="cb344-9"><a href="general-statistics.html#cb344-9" tabindex="-1"></a><span class="co"># Plot a bar chart</span></span>
<span id="cb344-10"><a href="general-statistics.html#cb344-10" tabindex="-1"></a><span class="fu">ggplot</span>(PurchasebyAge, </span>
<span id="cb344-11"><a href="general-statistics.html#cb344-11" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> Age.Group, <span class="at">y =</span> Gross.Amount)) <span class="sc">+</span></span>
<span id="cb344-12"><a href="general-statistics.html#cb344-12" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">fill=</span><span class="st">&quot;blue&quot;</span>, <span class="at">color=</span><span class="st">&quot;white&quot;</span>) <span class="sc">+</span></span>
<span id="cb344-13"><a href="general-statistics.html#cb344-13" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb344-14"><a href="general-statistics.html#cb344-14" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Average Gross Amount by Age Group&quot;</span>, </span>
<span id="cb344-15"><a href="general-statistics.html#cb344-15" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Age Group&quot;</span>, </span>
<span id="cb344-16"><a href="general-statistics.html#cb344-16" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Average Gross Amount&quot;</span>) <span class="sc">+</span></span>
<span id="cb344-17"><a href="general-statistics.html#cb344-17" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-137-1.png" width="672" /></p>
<p>All the age group had an almost equal average spending on the ecommerce store.</p>
<p>What if we calculated the total spending for each age group? That would be interesting! Lets calculate and plot a bar chart to represent that.</p>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb345-1"><a href="general-statistics.html#cb345-1" tabindex="-1"></a><span class="co"># Aggregate by sum</span></span>
<span id="cb345-2"><a href="general-statistics.html#cb345-2" tabindex="-1"></a>PurchasebyAge <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(Gross.Amount <span class="sc">~</span> Age.Group,</span>
<span id="cb345-3"><a href="general-statistics.html#cb345-3" tabindex="-1"></a>                           <span class="at">data =</span> ecommerce,</span>
<span id="cb345-4"><a href="general-statistics.html#cb345-4" tabindex="-1"></a>                           <span class="at">FUN =</span> sum</span>
<span id="cb345-5"><a href="general-statistics.html#cb345-5" tabindex="-1"></a>                           )</span>
<span id="cb345-6"><a href="general-statistics.html#cb345-6" tabindex="-1"></a></span>
<span id="cb345-7"><a href="general-statistics.html#cb345-7" tabindex="-1"></a><span class="co"># Plot a bar chart</span></span>
<span id="cb345-8"><a href="general-statistics.html#cb345-8" tabindex="-1"></a><span class="fu">ggplot</span>(PurchasebyAge, </span>
<span id="cb345-9"><a href="general-statistics.html#cb345-9" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> Age.Group, <span class="at">y =</span> Gross.Amount)) <span class="sc">+</span></span>
<span id="cb345-10"><a href="general-statistics.html#cb345-10" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">fill=</span><span class="st">&quot;blue&quot;</span>, <span class="at">color=</span><span class="st">&quot;white&quot;</span>) <span class="sc">+</span></span>
<span id="cb345-11"><a href="general-statistics.html#cb345-11" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb345-12"><a href="general-statistics.html#cb345-12" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Total Gross Amount by Age Group&quot;</span>, </span>
<span id="cb345-13"><a href="general-statistics.html#cb345-13" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Age Group&quot;</span>, </span>
<span id="cb345-14"><a href="general-statistics.html#cb345-14" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Total Gross Amount&quot;</span>) <span class="sc">+</span></span>
<span id="cb345-15"><a href="general-statistics.html#cb345-15" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-138-1.png" width="672" /></p>
<p>Age 25 - 45 had the highest total spending in the ecommerce store while age of 60 and above had the least total spending.</p>
<ol start="6" style="list-style-type: lower-alpha">
<li><strong>Boxplots and Violin Plots</strong></li>
</ol>
<p>Box plot is a type of chart that uses boxes and lines to show distributions of one or more groups of a continuous numeric data. They provide a high-level information at a glance for instance the data symmetry, skew and variance. They can also be used to show outliers within a data set. This is the only chart that can effectively give the measure of spread and central tendency(median, quartiles and range).</p>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>We will plot a boxplot of the Net Amount spent on the ecommerce store.</p>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb346-1"><a href="general-statistics.html#cb346-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb346-2"><a href="general-statistics.html#cb346-2" tabindex="-1"></a></span>
<span id="cb346-3"><a href="general-statistics.html#cb346-3" tabindex="-1"></a><span class="co"># Plot a boxplot</span></span>
<span id="cb346-4"><a href="general-statistics.html#cb346-4" tabindex="-1"></a><span class="fu">ggplot</span>(ecommerce, <span class="fu">aes</span>(<span class="at">y=</span>Net.Amount))<span class="sc">+</span></span>
<span id="cb346-5"><a href="general-statistics.html#cb346-5" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill=</span><span class="st">&quot;black&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-139-1.png" width="672" /></p>
<p>The upper and lower boundaries represents the upper(Q3) and lower(Q1) quartiles respectively. In out case the upper quartile is about 4200INR and the lower quartile is approximately 1500. The median is represented by the line cutting through the box, whereby in our case is approximately 2800 INR. The maximum value is the uppermost point of the boxplot which is approximately 8300INR. Finally, the minimum is the bottom of the plot which is approximately 350INR.</p>
<p><span style="color: green;"><strong>Practical Exercise</strong></span></p>
<p>To enhance your understanding in basic data visualizations, you will be required to use the inbuilt diamonds data set and follow the instructions below.</p>
<ol style="list-style-type: lower-roman">
<li>Plot a bar chart to show the count of diamonds by <code>cut</code> quality.</li>
<li>Generate a scatter plot to show the relationship between <code>carat</code> and <code>price</code>.</li>
<li>Plot a histogram of the <code>price</code> of diamonds.</li>
<li>Create a boxplot to compare the price distributions across different different diamond <code>color</code> categories.</li>
<li>Visualize the male and female passengers in each class.</li>
</ol>
<p><strong>Hint: </strong> The titanic data set is loaded as below</p>
<pre><code>data(&quot;diamonds&quot;)</code></pre>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<ul>
<li>Load the required libraries and data set.</li>
</ul>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb348-1"><a href="general-statistics.html#cb348-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2) <span class="co"># library for visualization</span></span>
<span id="cb348-2"><a href="general-statistics.html#cb348-2" tabindex="-1"></a></span>
<span id="cb348-3"><a href="general-statistics.html#cb348-3" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;diamonds&quot;</span>) <span class="co"># Load diamonds data </span></span></code></pre></div>
<ol style="list-style-type: lower-roman">
<li>Plot a bar chart to show the count of diamonds by <code>cut</code> quality.</li>
</ol>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb349-1"><a href="general-statistics.html#cb349-1" tabindex="-1"></a><span class="fu">ggplot</span>(diamonds, </span>
<span id="cb349-2"><a href="general-statistics.html#cb349-2" tabindex="-1"></a>        <span class="fu">aes</span>(<span class="at">x=</span>cut)) <span class="sc">+</span> </span>
<span id="cb349-3"><a href="general-statistics.html#cb349-3" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill=</span><span class="st">&quot;skyblue&quot;</span>) <span class="sc">+</span> </span>
<span id="cb349-4"><a href="general-statistics.html#cb349-4" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb349-5"><a href="general-statistics.html#cb349-5" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Count of diamonds by cut&quot;</span>,</span>
<span id="cb349-6"><a href="general-statistics.html#cb349-6" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Cut Quality&quot;</span>,</span>
<span id="cb349-7"><a href="general-statistics.html#cb349-7" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Count&quot;</span></span>
<span id="cb349-8"><a href="general-statistics.html#cb349-8" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb349-9"><a href="general-statistics.html#cb349-9" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-141-1.png" width="672" /></p>
<p>Most diamonds had an ideal cut quality while least of them had a fair cut quality</p>
<ol start="2" style="list-style-type: lower-roman">
<li>Generate a scatter plot to show the relationship between <code>carat</code> and <code>price</code>.</li>
</ol>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb350-1"><a href="general-statistics.html#cb350-1" tabindex="-1"></a><span class="fu">ggplot</span>(diamonds,</span>
<span id="cb350-2"><a href="general-statistics.html#cb350-2" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> carat, <span class="at">y =</span> price)) <span class="sc">+</span></span>
<span id="cb350-3"><a href="general-statistics.html#cb350-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;darkblue&quot;</span>, <span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb350-4"><a href="general-statistics.html#cb350-4" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb350-5"><a href="general-statistics.html#cb350-5" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Carat vs Price&quot;</span>, </span>
<span id="cb350-6"><a href="general-statistics.html#cb350-6" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Carat&quot;</span>,</span>
<span id="cb350-7"><a href="general-statistics.html#cb350-7" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Price&quot;</span></span>
<span id="cb350-8"><a href="general-statistics.html#cb350-8" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb350-9"><a href="general-statistics.html#cb350-9" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-142-1.png" width="672" /></p>
<p>The relationship between Carat and Price was almost directly proportional where higher carat was equal to higher prices.</p>
<ol start="3" style="list-style-type: lower-roman">
<li>Plot a histogram of the <code>price</code> of diamonds.</li>
</ol>
<div class="sourceCode" id="cb351"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb351-1"><a href="general-statistics.html#cb351-1" tabindex="-1"></a><span class="fu">ggplot</span>(diamonds, </span>
<span id="cb351-2"><a href="general-statistics.html#cb351-2" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> price)) <span class="sc">+</span> </span>
<span id="cb351-3"><a href="general-statistics.html#cb351-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">30</span>, <span class="at">fill=</span><span class="st">&quot;orange&quot;</span>, <span class="at">color=</span><span class="st">&quot;black&quot;</span>) <span class="sc">+</span> </span>
<span id="cb351-4"><a href="general-statistics.html#cb351-4" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb351-5"><a href="general-statistics.html#cb351-5" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Diamond Prices distribution&quot;</span>, </span>
<span id="cb351-6"><a href="general-statistics.html#cb351-6" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Price&quot;</span>, </span>
<span id="cb351-7"><a href="general-statistics.html#cb351-7" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Count&quot;</span></span>
<span id="cb351-8"><a href="general-statistics.html#cb351-8" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb351-9"><a href="general-statistics.html#cb351-9" tabindex="-1"></a>  <span class="fu">theme_light</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-143-1.png" width="672" /></p>
<p>The distribution of diamond prices was right-skewed. Most of the diamonds had prices lower than 5000</p>
<ol start="4" style="list-style-type: lower-roman">
<li>Create a boxplot to compare the price distributions across different different diamond <code>color</code> categories.</li>
</ol>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb352-1"><a href="general-statistics.html#cb352-1" tabindex="-1"></a><span class="fu">ggplot</span>(diamonds,</span>
<span id="cb352-2"><a href="general-statistics.html#cb352-2" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>color, <span class="at">y=</span>price, <span class="at">fill=</span>color)) <span class="sc">+</span> </span>
<span id="cb352-3"><a href="general-statistics.html#cb352-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb352-4"><a href="general-statistics.html#cb352-4" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb352-5"><a href="general-statistics.html#cb352-5" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Diamond Prices distribution by color&quot;</span>, </span>
<span id="cb352-6"><a href="general-statistics.html#cb352-6" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Diamond color&quot;</span>,</span>
<span id="cb352-7"><a href="general-statistics.html#cb352-7" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Price&quot;</span></span>
<span id="cb352-8"><a href="general-statistics.html#cb352-8" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb352-9"><a href="general-statistics.html#cb352-9" tabindex="-1"></a>  <span class="fu">theme_dark</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-144-1.png" width="672" /></p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>
</div>
<div id="inferential-statistics" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Inferential Statistics<a href="general-statistics.html#inferential-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="introduction-to-hypothesis-testing" class="section level3 hasAnchor" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Introduction to Hypothesis Testing<a href="general-statistics.html#introduction-to-hypothesis-testing" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="concept-of-hypothesis-testing" class="section level4 hasAnchor" number="4.3.1.1">
<h4><span class="header-section-number">4.3.1.1</span> Concept of Hypothesis Testing<a href="general-statistics.html#concept-of-hypothesis-testing" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Hypothesis testing is a type of statistical analysis that is used to make assumptions of a population based on a sample of data. It is particularly used to find the relationship between two variables(populations). A real life example of hypothesis testing is that a teacher may assume that 60% of the students come from a middle-class family. There are two types of hypothesis;</p>
<ul>
<li>Null hypothesis(<span class="math inline">\(H_0\)</span>)</li>
<li>Alternate hypothesis (<span class="math inline">\(H_1\)</span> or <span class="math inline">\(H_a\)</span>)</li>
</ul>
<p><strong>Null hypothesis</strong> is states that there is no effect or no difference(<span class="math inline">\(\mu = 0\)</span>). For instance there is no effect of standards of living to college admissions. <strong>Alternate hypothesis</strong> is the opposite and contradicts the null hypothesis. It provide evidence for what the statistician is trying to find(<span class="math inline">\(\mu \neq 0\)</span>). In this case, the standards of living have an effect on college admissions.</p>
<p>The important aspects before conducting hypothesis testing are;-</p>
<ul>
<li><em>Significance level.</em> It is the probability of rejecting the null hypothesis when it is actually true.</li>
<li><em>P-Value</em> is the probability of obtaining a test statistic at least as extreme as the one observed, given the null hypothesis is true. Most hypothesis testing projects are set at 0.05. Less than 0.05(or the set value) indicates the null the test is statistically significant and the null hypothesis should be rejected. Otherwise, the test is statistically insignificant and the null hypothesis is not rejected.</li>
<li><em>Test statistic</em> also called T-statistic is a standardized value calcluated during a hypothesis test. It cab z-test or a t-test.
-<em>Decision rule</em> is based on the calculated p-value and the significant level. In a hypothesis test where the significant and the p-value is 0.03444 the null hypothesis is not rejected.</li>
</ul>
<p>Now that you are familiar with the hypothesis testing aspects, take the following steps to perform hypothesis testing;-</p>
<ol style="list-style-type: lower-roman">
<li>Formulating the hypothesis by defining the null and alternate hypothesis.</li>
<li>Collect and analyze the data.</li>
<li>Choose a significant level(<span class="math inline">\(a\)</span>) and calculate the p-value.</li>
<li>Make a decision by comparing the p-value to the significant level.</li>
<li>Conclude your analysis results.</li>
</ol>
</div>
<div id="t-tests" class="section level4 hasAnchor" number="4.3.1.2">
<h4><span class="header-section-number">4.3.1.2</span> T-tests<a href="general-statistics.html#t-tests" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li><em>One-Sample t-test</em></li>
</ul>
<p>One sample t-test is a statistical method used to find if the mean of a sample is different from the population(or preassumed) mean.</p>
<p>It is based on the t-distribution(most observations fall close to the mean, and the rest of the observations make up the tails on either side) and is commonly used when dealing with small sample sizes. One sample t-test is especially performed where the population standard deviation is unknown.</p>
<p>Below is the formula for one sample t-test
<span class="math display">\[t={{\overline{X}-\mu}\over s / \sqrt{n}}\]</span></p>
<p>where;</p>
<ol style="list-style-type: lower-roman">
<li><span class="math inline">\(t\)</span>: the one sample t-test value. t-test statistic</li>
<li><span class="math inline">\(n\)</span>: the number of the observations in the sample</li>
<li><span class="math inline">\(\overline{X}\)</span>: is the sample mean</li>
<li><span class="math inline">\(s\)</span>: standard deviation of the sample</li>
<li><span class="math inline">\(\mu\)</span>: Hypothesized population mean</li>
</ol>
<p>The result <span class="math inline">\(t\)</span>, simply measures how many standard errors the sample mean is away from the hypothesized population mean.</p>
<p>Before conducting t-test, there is a need to establish the null(H0) and alternate hypothesis(Ha) where;</p>
<ul>
<li><em>Null Hypothesis(H0)</em>: There is no significant difference between the sample mean and the population(hypothesized) mean.</li>
<li><em>ALternate Hypothesis(Ha)</em>: There is a significant difference between the sample mean and the population mean.</li>
</ul>
<p>P-value is the probability value that tells you how likely is that your data could have occurred under null hypothesis. In our case a p-value of below 0.05 is considered to be statistically significant and the null value is rejected. The vice versa is true</p>
<p>Lets perform a t-test using R;</p>
<p>We will generate sample data</p>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb353-1"><a href="general-statistics.html#cb353-1" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb353-2"><a href="general-statistics.html#cb353-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb353-3"><a href="general-statistics.html#cb353-3" tabindex="-1"></a></span>
<span id="cb353-4"><a href="general-statistics.html#cb353-4" tabindex="-1"></a><span class="co"># Generate random student marks (out of 100)</span></span>
<span id="cb353-5"><a href="general-statistics.html#cb353-5" tabindex="-1"></a>student_marks <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean =</span> <span class="dv">65</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span>
<span id="cb353-6"><a href="general-statistics.html#cb353-6" tabindex="-1"></a></span>
<span id="cb353-7"><a href="general-statistics.html#cb353-7" tabindex="-1"></a><span class="co"># Display the first few marks</span></span>
<span id="cb353-8"><a href="general-statistics.html#cb353-8" tabindex="-1"></a><span class="fu">head</span>(student_marks)</span></code></pre></div>
<pre><code>## [1] 59.39524 62.69823 80.58708 65.70508 66.29288 82.15065</code></pre>
<p>Perform the t-test</p>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb355-1"><a href="general-statistics.html#cb355-1" tabindex="-1"></a><span class="co"># Conduct one-sample t-test</span></span>
<span id="cb355-2"><a href="general-statistics.html#cb355-2" tabindex="-1"></a>t_test_result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(student_marks, <span class="at">mu =</span> <span class="dv">70</span>)</span>
<span id="cb355-3"><a href="general-statistics.html#cb355-3" tabindex="-1"></a></span>
<span id="cb355-4"><a href="general-statistics.html#cb355-4" tabindex="-1"></a><span class="co"># Display the t-test result</span></span>
<span id="cb355-5"><a href="general-statistics.html#cb355-5" tabindex="-1"></a><span class="fu">print</span>(t_test_result)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  student_marks
## t = -3.0546, df = 29, p-value = 0.004797
## alternative hypothesis: true mean is not equal to 70
## 95 percent confidence interval:
##  60.86573 68.19219
## sample estimates:
## mean of x 
##  64.52896</code></pre>
<p><span style="color: green;"><strong>Practical exercise</strong></span></p>
<p>Conduct one sample t-test on the sepal length of the setosa iris. The pre-assumed mean is 5.84 units.</p>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<ul>
<li>Null Hypothesis(<span class="math inline">\(H_0\)</span>): There is no significant difference between the setosa sepal length mean and the pre-assumed mean</li>
<li>Alternate Hypothesis(<span class="math inline">\(H_a\)</span>): There is a significant difference between the setosa sepal length and the pre-assumed mean</li>
</ul>
<p><strong>Note</strong>: If the pre-assumed mean is not given in the question therefore the whole population mean is used(as the pre-assumed mean). In this case, the setosa sepal length mean of the whole iris species.</p>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb357-1"><a href="general-statistics.html#cb357-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb357-2"><a href="general-statistics.html#cb357-2" tabindex="-1"></a><span class="co"># Load the data</span></span>
<span id="cb357-3"><a href="general-statistics.html#cb357-3" tabindex="-1"></a><span class="fu">data</span>(iris)</span>
<span id="cb357-4"><a href="general-statistics.html#cb357-4" tabindex="-1"></a></span>
<span id="cb357-5"><a href="general-statistics.html#cb357-5" tabindex="-1"></a><span class="co"># Get the setosa sepal length</span></span>
<span id="cb357-6"><a href="general-statistics.html#cb357-6" tabindex="-1"></a>setosa <span class="ot">&lt;-</span> iris <span class="sc">%&gt;%</span> </span>
<span id="cb357-7"><a href="general-statistics.html#cb357-7" tabindex="-1"></a>  <span class="fu">filter</span>(Species<span class="sc">==</span><span class="st">&quot;setosa&quot;</span>)</span>
<span id="cb357-8"><a href="general-statistics.html#cb357-8" tabindex="-1"></a></span>
<span id="cb357-9"><a href="general-statistics.html#cb357-9" tabindex="-1"></a>setosa.sepal.length <span class="ot">&lt;-</span> setosa<span class="sc">$</span>Sepal.Length</span>
<span id="cb357-10"><a href="general-statistics.html#cb357-10" tabindex="-1"></a></span>
<span id="cb357-11"><a href="general-statistics.html#cb357-11" tabindex="-1"></a><span class="co"># Calculate one-sample ttest </span></span>
<span id="cb357-12"><a href="general-statistics.html#cb357-12" tabindex="-1"></a><span class="do">## Set the pre-assumed mean </span></span>
<span id="cb357-13"><a href="general-statistics.html#cb357-13" tabindex="-1"></a>pre_assumed_mean <span class="ot">&lt;-</span> <span class="fl">5.84</span> <span class="co"># as in the question</span></span>
<span id="cb357-14"><a href="general-statistics.html#cb357-14" tabindex="-1"></a></span>
<span id="cb357-15"><a href="general-statistics.html#cb357-15" tabindex="-1"></a>t_test_result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(setosa.sepal.length, <span class="at">mu =</span> pre_assumed_mean)</span>
<span id="cb357-16"><a href="general-statistics.html#cb357-16" tabindex="-1"></a></span>
<span id="cb357-17"><a href="general-statistics.html#cb357-17" tabindex="-1"></a><span class="fu">print</span>(t_test_result)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  setosa.sepal.length
## t = -16.73, df = 49, p-value &lt; 2.2e-16
## alternative hypothesis: true mean is not equal to 5.84
## 95 percent confidence interval:
##  4.905824 5.106176
## sample estimates:
## mean of x 
##     5.006</code></pre>
<p>The p-value is much below 0.05, therefore the null hypothesis is rejected. It is concluded that there is a significant difference between the sepal length mean and the pre-assumed mean</p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>
<ul>
<li><em>Two-Sample t-test</em></li>
</ul>
<p>Unlike one sample t-test where a sample population is tested against a pre-assumed mean, the Tow-sample t-test determines if there is a significant difference between the means of two independent populations.</p>
<p>The practical application of two-sample t-test can be when comparing the test scores of two classes. This helps the statistician to understand if one class did better than the other one or it’s just a matter of luck.</p>
<p>These are the prerequisites before conducting a two-sample t-test;</p>
<ol style="list-style-type: lower-roman">
<li>The groups contain separate data with a similar distribution.</li>
<li>The two populations have a normal(typical bell-curve) distribution.</li>
<li>The two sample populations have a similar variations</li>
</ol>
<p>The two sample t-test is calculated by;
<img src="images/two-sample-ttest.jpg" /></p>
<p>Where;</p>
<ul>
<li><span class="math inline">\(\overline{x}_1\)</span> and <span class="math inline">\(\overline{x}_2\)</span> are the mean of the first sample and the second sample respectively</li>
<li><span class="math inline">\(s_{1}\)</span> and <span class="math inline">\(s_{2}\)</span> are the standard deviation of sample 1 and sample 2 respectively</li>
<li><span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span> are the sample sizes of the first and second sample respectively.</li>
</ul>
<p>Let create a random population of student scores for two classes and perform two-sample t-test in R;</p>
<div class="sourceCode" id="cb359"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb359-1"><a href="general-statistics.html#cb359-1" tabindex="-1"></a><span class="co"># Generate the population sample</span></span>
<span id="cb359-2"><a href="general-statistics.html#cb359-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb359-3"><a href="general-statistics.html#cb359-3" tabindex="-1"></a>group_A_scores <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">25</span>, <span class="at">mean =</span> <span class="dv">75</span>, <span class="at">sd =</span> <span class="dv">8</span>)  <span class="co"># Group A</span></span>
<span id="cb359-4"><a href="general-statistics.html#cb359-4" tabindex="-1"></a>group_B_scores <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">25</span>, <span class="at">mean =</span> <span class="dv">80</span>, <span class="at">sd =</span> <span class="dv">10</span>)  <span class="co"># Group B</span></span>
<span id="cb359-5"><a href="general-statistics.html#cb359-5" tabindex="-1"></a></span>
<span id="cb359-6"><a href="general-statistics.html#cb359-6" tabindex="-1"></a><span class="co"># Display the first few scores of each group</span></span>
<span id="cb359-7"><a href="general-statistics.html#cb359-7" tabindex="-1"></a><span class="fu">head</span>(group_A_scores)</span></code></pre></div>
<pre><code>## [1] 70.51619 73.15858 87.46967 75.56407 76.03430 88.72052</code></pre>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb361-1"><a href="general-statistics.html#cb361-1" tabindex="-1"></a><span class="fu">head</span>(group_B_scores)</span></code></pre></div>
<pre><code>## [1] 63.13307 88.37787 81.53373 68.61863 92.53815 84.26464</code></pre>
<p>Performing the two sample t-test. Lets set the confidence level to 95%(0.95)</p>
<div class="sourceCode" id="cb363"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb363-1"><a href="general-statistics.html#cb363-1" tabindex="-1"></a>ttest_result <span class="ot">=</span> <span class="fu">t.test</span>(group_A_scores, group_B_scores, </span>
<span id="cb363-2"><a href="general-statistics.html#cb363-2" tabindex="-1"></a>                      <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">paired =</span> <span class="cn">FALSE</span>,</span>
<span id="cb363-3"><a href="general-statistics.html#cb363-3" tabindex="-1"></a>                      <span class="at">var.equal =</span> <span class="cn">FALSE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span>
<span id="cb363-4"><a href="general-statistics.html#cb363-4" tabindex="-1"></a></span>
<span id="cb363-5"><a href="general-statistics.html#cb363-5" tabindex="-1"></a>ttest_result</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  group_A_scores and group_B_scores
## t = -2.6403, df = 46.312, p-value = 0.01125
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -11.080984  -1.495049
## sample estimates:
## mean of x mean of y 
##  74.73336  81.02137</code></pre>
<ul>
<li><strong>t-value = -2.6403</strong>: This indicates the difference between the means of the two groups, in terms of standard errors. A higher absolute value suggests a larger difference.</li>
<li><strong>Degrees of freedom (df) = 46.312</strong>: This reflects the sample size and variability in the data.</li>
<li><strong>p-value = 0.01125</strong>: Since the p-value is less than 0.05, we reject the null hypothesis. This suggests that the difference in means between Group A and Group B is statistically significant.</li>
<li><strong>95% confidence interval: (-11.08, -1.50)</strong>: This indicates that we are 95% confident that the true difference in means lies between -11.08 and -1.50.</li>
<li><strong>Mean of x (Group A) = 74.73, Mean of y (Group B) = 81.02</strong>: The average score of Group B is higher than Group A.</li>
</ul>
<p>In summary, the test shows a significant difference between the means of the two groups, with Group B having higher scores</p>
<p><span style="color: green;"><strong>Practical exercise</strong></span></p>
<p>Using the iris data set, compare the petal length of the <em>versicolor</em> and <em>virginica</em> species using two-sample t-test. Interpret the results</p>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<p>Lets formulate the hypothesis;</p>
<ul>
<li>Null Hypothesis(<span class="math inline">\(H_0\)</span>): There is no significant difference between the mean of virginica and the mean of versicolor</li>
<li>Alternate Hypothesis(<span class="math inline">\(H_a\)</span>): There is a significant difference between the mean of virginica and the versicolor</li>
</ul>
<div class="sourceCode" id="cb365"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb365-1"><a href="general-statistics.html#cb365-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb365-2"><a href="general-statistics.html#cb365-2" tabindex="-1"></a></span>
<span id="cb365-3"><a href="general-statistics.html#cb365-3" tabindex="-1"></a><span class="co"># Load the data </span></span>
<span id="cb365-4"><a href="general-statistics.html#cb365-4" tabindex="-1"></a><span class="fu">data</span>(iris)</span>
<span id="cb365-5"><a href="general-statistics.html#cb365-5" tabindex="-1"></a></span>
<span id="cb365-6"><a href="general-statistics.html#cb365-6" tabindex="-1"></a><span class="co"># Retrieve the data for the two species </span></span>
<span id="cb365-7"><a href="general-statistics.html#cb365-7" tabindex="-1"></a><span class="do">## Virginica petal length</span></span>
<span id="cb365-8"><a href="general-statistics.html#cb365-8" tabindex="-1"></a>virginica <span class="ot">&lt;-</span> iris<span class="sc">%&gt;%</span> </span>
<span id="cb365-9"><a href="general-statistics.html#cb365-9" tabindex="-1"></a>  <span class="fu">filter</span>(Species<span class="sc">==</span><span class="st">&quot;virginica&quot;</span>)</span>
<span id="cb365-10"><a href="general-statistics.html#cb365-10" tabindex="-1"></a></span>
<span id="cb365-11"><a href="general-statistics.html#cb365-11" tabindex="-1"></a>virginica.petal.length <span class="ot">&lt;-</span> virginica<span class="sc">$</span>Petal.Length</span>
<span id="cb365-12"><a href="general-statistics.html#cb365-12" tabindex="-1"></a></span>
<span id="cb365-13"><a href="general-statistics.html#cb365-13" tabindex="-1"></a><span class="do">## Versicolor petal length</span></span>
<span id="cb365-14"><a href="general-statistics.html#cb365-14" tabindex="-1"></a>versicolor <span class="ot">&lt;-</span> iris<span class="sc">%&gt;%</span> </span>
<span id="cb365-15"><a href="general-statistics.html#cb365-15" tabindex="-1"></a>  <span class="fu">filter</span>(Species<span class="sc">==</span><span class="st">&quot;versicolor&quot;</span>)</span>
<span id="cb365-16"><a href="general-statistics.html#cb365-16" tabindex="-1"></a></span>
<span id="cb365-17"><a href="general-statistics.html#cb365-17" tabindex="-1"></a>versicolor.petal.length <span class="ot">&lt;-</span> versicolor<span class="sc">$</span>Petal.Length</span>
<span id="cb365-18"><a href="general-statistics.html#cb365-18" tabindex="-1"></a></span>
<span id="cb365-19"><a href="general-statistics.html#cb365-19" tabindex="-1"></a><span class="co"># Conduct two-sample t-test</span></span>
<span id="cb365-20"><a href="general-statistics.html#cb365-20" tabindex="-1"></a>ttest_result <span class="ot">=</span> <span class="fu">t.test</span>(virginica.petal.length, versicolor.petal.length, </span>
<span id="cb365-21"><a href="general-statistics.html#cb365-21" tabindex="-1"></a>                      <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">paired =</span> <span class="cn">FALSE</span>,</span>
<span id="cb365-22"><a href="general-statistics.html#cb365-22" tabindex="-1"></a>                      <span class="at">var.equal =</span> <span class="cn">FALSE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span>
<span id="cb365-23"><a href="general-statistics.html#cb365-23" tabindex="-1"></a></span>
<span id="cb365-24"><a href="general-statistics.html#cb365-24" tabindex="-1"></a>ttest_result</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  virginica.petal.length and versicolor.petal.length
## t = 12.604, df = 95.57, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  1.08851 1.49549
## sample estimates:
## mean of x mean of y 
##     5.552     4.260</code></pre>
<p>With a p-value of less than 0.05, the null hypothesis is rejected. It is concluded that there is a significant difference between the mean of virginica species and the mean of versicolor species.</p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>
</div>
<div id="anova-analysis-of-variance" class="section level4 hasAnchor" number="4.3.1.3">
<h4><span class="header-section-number">4.3.1.3</span> ANOVA (Analysis of Variance)<a href="general-statistics.html#anova-analysis-of-variance" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>ANOVA is a statistical test used to analyze the difference between the means of more than two groups. This is different from the ttest that analyzes one or two groups, it uses F test to find the statistical significance. Multiple means are compared at once and if one mean is different the hypothesis is rejected.</p>
<p>The F test compares the variance in each group from the overal group variance.</p>
<p>An practical example of ANOVA is where a farmer wants to test the effect of three different fertilizers on the crop yield. The difference in the crop yield will be calculated.</p>
<p>Before conducting ANOVA, the following assumptions are made;</p>
<ol style="list-style-type: lower-roman">
<li><strong>Independence of observations</strong>: the data was collected using statistically valid sampling methods and there are no hidden relationships among the observations.</li>
<li><strong>Normal distribution</strong>: the dependent variable should follow a normal distribution.</li>
<li><strong>Homogeinity of variance</strong>: All the groups being tested should have similar variations.</li>
</ol>
<p>Lets calculate the ANOVA using the the crop yield data set. The fertilizer are in three categories; 1, 2 and 3</p>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb367-1"><a href="general-statistics.html#cb367-1" tabindex="-1"></a><span class="co"># Load the data set </span></span>
<span id="cb367-2"><a href="general-statistics.html#cb367-2" tabindex="-1"></a>crop_df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/cropdata.csv&quot;</span>)</span>
<span id="cb367-3"><a href="general-statistics.html#cb367-3" tabindex="-1"></a><span class="fu">head</span>(crop_df) <span class="co"># view the first few rows of the data set</span></span></code></pre></div>
<pre><code>##   density block fertilizer    yield
## 1       1     1          1 177.2287
## 2       2     2          1 177.5500
## 3       1     3          1 176.4085
## 4       2     4          1 177.7036
## 5       1     1          1 177.1255
## 6       2     2          1 176.7783</code></pre>
<div class="sourceCode" id="cb369"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb369-1"><a href="general-statistics.html#cb369-1" tabindex="-1"></a><span class="co"># Calculate one way ANOVA </span></span>
<span id="cb369-2"><a href="general-statistics.html#cb369-2" tabindex="-1"></a>anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(yield <span class="sc">~</span> fertilizer, <span class="at">data =</span> crop_df)</span>
<span id="cb369-3"><a href="general-statistics.html#cb369-3" tabindex="-1"></a>anova</span></code></pre></div>
<pre><code>## Call:
##    aov(formula = yield ~ fertilizer, data = crop_df)
## 
## Terms:
##                 fertilizer Residuals
## Sum of Squares     5.74322  36.21101
## Deg. of Freedom          1        94
## 
## Residual standard error: 0.6206638
## Estimated effects may be unbalanced</code></pre>
<p>The ANOVA output provides insights into the variation in crop yield explained by the fertilizer type. Here’s a detailed breakdown of the results:</p>
<ul>
<li><p><strong>Sum of Squares (fertilizer) = 5.74322</strong>: This value represents the variation in crop yield that can be attributed to the different types of fertilizers used in the experiment. In this case, 5.74322 units of the total variation are explained by fertilizer differences.</p></li>
<li><p><strong>Sum of Squares (Residuals) = 36.21101</strong>: This is the unexplained variation in crop yield, also known as the error term. This shows how much of the variation is due to factors not accounted for in the model, such as environmental factors or random error.</p></li>
<li><p><strong>Degrees of Freedom (fertilizer) = 1</strong>: There is only 1 degree of freedom for the fertilizer factor, which means there was a comparison between two groups (likely two fertilizer types or one fertilizer versus a control).</p></li>
<li><p><strong>Degrees of Freedom (Residuals) = 94</strong>: There are 94 degrees of freedom associated with the residuals. This is related to the total number of observations minus the number of groups being compared. In this case, the large degrees of freedom indicate a sizable data set.</p></li>
<li><p><strong>Residual Standard Error = 0.6206638</strong>: This value represents the typical deviation of the observed yield values from the predicted values, given the current model. A lower residual standard error suggests a better fit of the model to the data, though this value needs to be interpreted in context.</p></li>
</ul>
<p>The results show that the fertilizer type explains some of the variation in crop yield (Sum of Squares = 5.74322), while a larger portion remains unexplained (Sum of Squares of Residuals = 36.21101). To fully interpret the significance of this effect, a p-value and F-statistic would typically be calculated, but these are not provided here. Additionally, the residual standard error (0.6206638) gives an indication of the spread of the data around the predicted values, but more information would be needed to assess the strength of the model’s fit.</p>
<p>In conclusion, while the fertilizer has some effect on crop yield, the overall variability and potential unbalanced data need further exploration for a complete understanding.</p>
<p><span style="color: green;"><strong>Practical exercise</strong></span></p>
<p>Perform ANOVA on the sepal width of the three species in the iris data set and interpret the results.</p>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<p>Lets formulate the hypothesis;</p>
<ul>
<li>Null Hypothesis(<span class="math inline">\(H_0\)</span>): There is no siginificant difference among the sepal width of all the iris species.</li>
<li>Alternate Hypothesis(<span class="math inline">\(H_a\)</span>): There is a signifincant difference among the sepal width of all the iris species</li>
</ul>
<div class="sourceCode" id="cb371"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb371-1"><a href="general-statistics.html#cb371-1" tabindex="-1"></a><span class="co"># Load the data </span></span>
<span id="cb371-2"><a href="general-statistics.html#cb371-2" tabindex="-1"></a><span class="fu">data</span>(iris)</span>
<span id="cb371-3"><a href="general-statistics.html#cb371-3" tabindex="-1"></a></span>
<span id="cb371-4"><a href="general-statistics.html#cb371-4" tabindex="-1"></a><span class="co"># Perform the ANOVA</span></span>
<span id="cb371-5"><a href="general-statistics.html#cb371-5" tabindex="-1"></a>anova_result <span class="ot">&lt;-</span> <span class="fu">aov</span>(Sepal.Width <span class="sc">~</span> Species, <span class="at">data =</span> iris)</span>
<span id="cb371-6"><a href="general-statistics.html#cb371-6" tabindex="-1"></a></span>
<span id="cb371-7"><a href="general-statistics.html#cb371-7" tabindex="-1"></a><span class="co"># Display the ANOVA table</span></span>
<span id="cb371-8"><a href="general-statistics.html#cb371-8" tabindex="-1"></a><span class="fu">summary</span>(anova_result)</span></code></pre></div>
<pre><code>##              Df Sum Sq Mean Sq F value Pr(&gt;F)    
## Species       2  11.35   5.672   49.16 &lt;2e-16 ***
## Residuals   147  16.96   0.115                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>it indicates that there are statistically significant differences in the mean <code>Sepal.Width</code> between the species.</p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>
</div>
<div id="chi-square-test" class="section level4 hasAnchor" number="4.3.1.4">
<h4><span class="header-section-number">4.3.1.4</span> Chi-Square Test<a href="general-statistics.html#chi-square-test" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>This is a statistical test that determines the difference between the observed and the expected data. It determines if the relationship between two categorical variables is due to chance or a relationship between them.</p>
<p>It is calculated by;
<span class="math display">\[x_{c}^{2} = \frac{\sum(O_{i}-E_{i})}{E_i}\]</span></p>
<p>Where;</p>
<ol style="list-style-type: lower-roman">
<li><span class="math inline">\(c\)</span> is the degree of freedom. This is a statistical calculation that represents the number of variables that can carry and is calculated to ensure the chi-square tests are statistically valid</li>
<li><span class="math inline">\(O\)</span> is the observed value</li>
<li><span class="math inline">\(E\)</span> is the expected value</li>
</ol>
<p>Lets perform Chi-square on a survey data from the <code>MASS</code> library. The survey data represents data from a survey conducted on students.</p>
<ul>
<li>Null Hypothesis (<span class="math inline">\(H_0\)</span>): The smoking habit is independent of the student’s exercise level</li>
<li>ALternate Hypothesis (<span class="math inline">\(H_a\)</span>): The smoking habit is dependent on the exercise level.</li>
</ul>
<p>Load the data</p>
<div class="sourceCode" id="cb373"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb373-1"><a href="general-statistics.html#cb373-1" tabindex="-1"></a><span class="co"># Load the library</span></span>
<span id="cb373-2"><a href="general-statistics.html#cb373-2" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;MASS&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     select</code></pre>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb376-1"><a href="general-statistics.html#cb376-1" tabindex="-1"></a><span class="fu">head</span>(survey) <span class="co"># view the data</span></span></code></pre></div>
<pre><code>##      Sex Wr.Hnd NW.Hnd W.Hnd    Fold Pulse    Clap Exer Smoke Height      M.I
## 1 Female   18.5   18.0 Right  R on L    92    Left Some Never 173.00   Metric
## 2   Male   19.5   20.5  Left  R on L   104    Left None Regul 177.80 Imperial
## 3   Male   18.0   13.3 Right  L on R    87 Neither None Occas     NA     &lt;NA&gt;
## 4   Male   18.8   18.9 Right  R on L    NA Neither None Never 160.00   Metric
## 5   Male   20.0   20.0 Right Neither    35   Right Some Never 165.00   Metric
## 6 Female   18.0   17.7 Right  L on R    64   Right Some Never 172.72 Imperial
##      Age
## 1 18.250
## 2 17.583
## 3 16.917
## 4 20.333
## 5 23.667
## 6 21.000</code></pre>
<p>Create a contigency table between the Smoke and the Exercise leel.</p>
<div class="sourceCode" id="cb378"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb378-1"><a href="general-statistics.html#cb378-1" tabindex="-1"></a><span class="co"># Create a contingency table with the needed variables.       </span></span>
<span id="cb378-2"><a href="general-statistics.html#cb378-2" tabindex="-1"></a>stu_data <span class="ot">=</span> <span class="fu">table</span>(survey<span class="sc">$</span>Smoke,survey<span class="sc">$</span>Exer) </span>
<span id="cb378-3"><a href="general-statistics.html#cb378-3" tabindex="-1"></a>                 </span>
<span id="cb378-4"><a href="general-statistics.html#cb378-4" tabindex="-1"></a><span class="fu">print</span>(stu_data)</span></code></pre></div>
<pre><code>##        
##         Freq None Some
##   Heavy    7    1    3
##   Never   87   18   84
##   Occas   12    3    4
##   Regul    9    1    7</code></pre>
<p>Perform the chi-square test on the <code>stu_data</code>, the contigency table.</p>
<div class="sourceCode" id="cb380"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb380-1"><a href="general-statistics.html#cb380-1" tabindex="-1"></a><span class="co"># applying chisq.test() function</span></span>
<span id="cb380-2"><a href="general-statistics.html#cb380-2" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">chisq.test</span>(stu_data))</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  stu_data
## X-squared = 5.4885, df = 6, p-value = 0.4828</code></pre>
<p>From the results, the p-value is 0.4828 which is greater than 0.05 therefore the null hypothesis is not rejected. It’c concluded that the smoking habit is independent of the exercise level since there is weak to now correlation between the <code>Smoke</code> and <code>Exer</code> variables.</p>
<p>Finally, lets visualize the results from the contigency table;</p>
<div class="sourceCode" id="cb382"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb382-1"><a href="general-statistics.html#cb382-1" tabindex="-1"></a><span class="co"># Visualize the data with a bar plot</span></span>
<span id="cb382-2"><a href="general-statistics.html#cb382-2" tabindex="-1"></a><span class="fu">barplot</span>(stu_data, <span class="at">beside =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;lightblue&quot;</span>, <span class="st">&quot;lightgreen&quot;</span>),</span>
<span id="cb382-3"><a href="general-statistics.html#cb382-3" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">&quot;Smoking Habits vs Exercise Levels&quot;</span>,</span>
<span id="cb382-4"><a href="general-statistics.html#cb382-4" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">&quot;Exercise Level&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Number of Students&quot;</span>)</span>
<span id="cb382-5"><a href="general-statistics.html#cb382-5" tabindex="-1"></a> </span>
<span id="cb382-6"><a href="general-statistics.html#cb382-6" tabindex="-1"></a><span class="co"># Add legend separately</span></span>
<span id="cb382-7"><a href="general-statistics.html#cb382-7" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;center&quot;</span>, <span class="at">legend =</span> <span class="fu">rownames</span>(stu_data), <span class="at">fill =</span> <span class="fu">c</span>(<span class="st">&quot;lightblue&quot;</span>, <span class="st">&quot;lightgreen&quot;</span>))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-156-1.png" width="672" /></p>
<p>You can see from the table, those students who never smoke lead in every exercise level while the heavy smokers are the least in every group.</p>
<p><span style="color: green;"><strong>Practical exercise</strong></span></p>
<p>Using the Iris data set, perform a Chi-square test to determine if there is a relationship between two categorical variables: the species (Species) and a new categorical variable that classifies sepal width (Sepal.Length) into categories (e.g., “Short”, “Medium”, “Long”).</p>
<ul>
<li>“Short”: below 3.0</li>
<li>“Medium”: above 3.0 to 3.8</li>
<li>“Long”: above 3.8</li>
</ul>
<p>Follow the steps below;</p>
<ol style="list-style-type: decimal">
<li>Create a new variable <code>sepal.Width.Category</code> in the data set by categorizing the Sepal.Width variable into 3 categories: <code>"Short"</code>, <code>"Medium"</code>, and <code>"Long"</code> (as per the defined ranges).</li>
<li>Perform a Chi-square test to see if there’s an association between the new <code>sepal.Width.Category</code> categories and the <code>Species</code> column.</li>
<li>Interpret the results of the Chi-square test</li>
</ol>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<p>Load the data set</p>
<div class="sourceCode" id="cb383"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb383-1"><a href="general-statistics.html#cb383-1" tabindex="-1"></a><span class="fu">data</span>(iris) </span></code></pre></div>
<ol style="list-style-type: decimal">
<li>Create a new variable <code>sepal.Width.Category</code> in the data set by categorizing the <code>Sepal.Width</code> variable into 3 categories: <code>"Short"</code>, <code>"Medium"</code>, and <code>"Long"</code> (as per the defined ranges).</li>
</ol>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb384-1"><a href="general-statistics.html#cb384-1" tabindex="-1"></a><span class="co"># Load necessary libraries</span></span>
<span id="cb384-2"><a href="general-statistics.html#cb384-2" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb384-3"><a href="general-statistics.html#cb384-3" tabindex="-1"></a></span>
<span id="cb384-4"><a href="general-statistics.html#cb384-4" tabindex="-1"></a><span class="co"># Create a new column &#39;Sepal_Width_Category&#39; based on conditions</span></span>
<span id="cb384-5"><a href="general-statistics.html#cb384-5" tabindex="-1"></a>iris <span class="ot">&lt;-</span> iris <span class="sc">%&gt;%</span></span>
<span id="cb384-6"><a href="general-statistics.html#cb384-6" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sepal.Width.Category =</span> <span class="fu">case_when</span>(</span>
<span id="cb384-7"><a href="general-statistics.html#cb384-7" tabindex="-1"></a>    Sepal.Width <span class="sc">&lt;</span> <span class="fl">3.0</span> <span class="sc">~</span> <span class="st">&quot;Short&quot;</span>,</span>
<span id="cb384-8"><a href="general-statistics.html#cb384-8" tabindex="-1"></a>    Sepal.Width <span class="sc">&gt;=</span> <span class="fl">3.0</span> <span class="sc">&amp;</span> Sepal.Width <span class="sc">&lt;=</span> <span class="fl">3.8</span> <span class="sc">~</span> <span class="st">&quot;Medium&quot;</span>,</span>
<span id="cb384-9"><a href="general-statistics.html#cb384-9" tabindex="-1"></a>    Sepal.Width <span class="sc">&gt;</span> <span class="fl">3.8</span> <span class="sc">~</span> <span class="st">&quot;Long&quot;</span></span>
<span id="cb384-10"><a href="general-statistics.html#cb384-10" tabindex="-1"></a>  ))</span>
<span id="cb384-11"><a href="general-statistics.html#cb384-11" tabindex="-1"></a></span>
<span id="cb384-12"><a href="general-statistics.html#cb384-12" tabindex="-1"></a><span class="co"># Display the first few rows to see the new column</span></span>
<span id="cb384-13"><a href="general-statistics.html#cb384-13" tabindex="-1"></a><span class="fu">head</span>(iris)</span></code></pre></div>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
## 5          5.0         3.6          1.4         0.2  setosa
## 6          5.4         3.9          1.7         0.4  setosa
##   sepal.Width.Category
## 1               Medium
## 2               Medium
## 3               Medium
## 4               Medium
## 5               Medium
## 6                 Long</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Perform a Chi-square test to see if there’s an association between the new <code>sepal.Width.Category</code> categories and the <code>Species</code> column.</li>
</ol>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb386-1"><a href="general-statistics.html#cb386-1" tabindex="-1"></a><span class="co"># Create a contigency table </span></span>
<span id="cb386-2"><a href="general-statistics.html#cb386-2" tabindex="-1"></a>sepal_width_data <span class="ot">=</span> <span class="fu">table</span>(iris<span class="sc">$</span>sepal.Width.Category,iris<span class="sc">$</span>Species) </span>
<span id="cb386-3"><a href="general-statistics.html#cb386-3" tabindex="-1"></a></span>
<span id="cb386-4"><a href="general-statistics.html#cb386-4" tabindex="-1"></a><span class="fu">print</span>(sepal_width_data)</span></code></pre></div>
<pre><code>##         
##          setosa versicolor virginica
##   Long        6          0         0
##   Medium     42         16        29
##   Short       2         34        21</code></pre>
<div class="sourceCode" id="cb388"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb388-1"><a href="general-statistics.html#cb388-1" tabindex="-1"></a><span class="co"># applying chisq.test() function</span></span>
<span id="cb388-2"><a href="general-statistics.html#cb388-2" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">chisq.test</span>(sepal_width_data))</span></code></pre></div>
<pre><code>## Warning in chisq.test(sepal_width_data): Chi-squared approximation may be
## incorrect</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  sepal_width_data
## X-squared = 50.918, df = 4, p-value = 2.322e-10</code></pre>
<p><strong>Intepret the results</strong></p>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>
</div>
</div>
</div>
<div id="hands-on-exercise-2" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> <span style="color: green;"><strong>Hands-on Exercise</strong></span><a href="general-statistics.html#hands-on-exercise-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>You are required to download the Groundhog Day Forecasts and Temperatures data set from <a href="https://www.kaggle.com/datasets/groundhogclub/groundhog-day">here</a>.</p>
<ul>
<li>Perform one sample t-test on February Average temperature. The pre-assumed mean is 35</li>
<li>Conduct two sample t-test between the North East average temperature for March and the overall March daily temperature</li>
<li>Perform ANOVA between the presence of Punxsutawney Phil and the February average temperature</li>
</ul>
<p>Interpret the results</p>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<p>Load the data</p>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb391-1"><a href="general-statistics.html#cb391-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/GroundhogDayForecastsandTemperaturesdata.csv&quot;</span>)</span></code></pre></div>
<ul>
<li>Perform one sample t-test on February Average temperature. The pre-assumed mean is 35</li>
</ul>
<p>Formulate the hypothesis
- Null hypothesis (<span class="math inline">\(H_0\)</span>): There is no significant difference between the February Average Temeprature mean and the pre-assumed mean
- Alternate Hypothesis(<span class="math inline">\(H_a\)</span>): There is a significant difference between the February Average Temperature and the pre-assumed mean.</p>
<div class="sourceCode" id="cb392"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb392-1"><a href="general-statistics.html#cb392-1" tabindex="-1"></a>one.sample.ttest <span class="ot">&lt;-</span> <span class="fu">t.test</span>(df<span class="sc">$</span>February.Average.Temperature, <span class="at">mu=</span><span class="dv">35</span>)</span>
<span id="cb392-2"><a href="general-statistics.html#cb392-2" tabindex="-1"></a></span>
<span id="cb392-3"><a href="general-statistics.html#cb392-3" tabindex="-1"></a><span class="co"># Display the results </span></span>
<span id="cb392-4"><a href="general-statistics.html#cb392-4" tabindex="-1"></a><span class="fu">print</span>(one.sample.ttest)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  df$February.Average.Temperature
## t = -4.061, df = 122, p-value = 8.671e-05
## alternative hypothesis: true mean is not equal to 35
## 95 percent confidence interval:
##  33.21928 34.38641
## sample estimates:
## mean of x 
##  33.80285</code></pre>
<p>The p-value is below 0.05, therefore the is enough evidence to reject the null hypothesis and conclude that there is a significant difference between the February Average Temperature and the pre-assumed mean(35).</p>
<ul>
<li>Conduct two sample t-test between the North East average temperature for March and the overall March daily temperature.</li>
</ul>
<p>Formulate the hypothesis:</p>
<ul>
<li>Null hypothesis(<span class="math inline">\(H_0\)</span>): There is no significant difference between the North East Average Temperature for March and the March daily temparature.</li>
<li>ALternate Hypothesis(<span class="math inline">\(H_a\)</span>): There is a significant difference between the North East Average Temperature and the March daily temparature.</li>
</ul>
<div class="sourceCode" id="cb394"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb394-1"><a href="general-statistics.html#cb394-1" tabindex="-1"></a><span class="co"># Perform two sample ttest</span></span>
<span id="cb394-2"><a href="general-statistics.html#cb394-2" tabindex="-1"></a>ttest_result <span class="ot">=</span> <span class="fu">t.test</span>(df<span class="sc">$</span>March.Average.Temperature..Northeast., </span>
<span id="cb394-3"><a href="general-statistics.html#cb394-3" tabindex="-1"></a>                      df<span class="sc">$</span>March.Average.Temperature, </span>
<span id="cb394-4"><a href="general-statistics.html#cb394-4" tabindex="-1"></a>                      <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">paired =</span> <span class="cn">FALSE</span>,</span>
<span id="cb394-5"><a href="general-statistics.html#cb394-5" tabindex="-1"></a>                      <span class="at">var.equal =</span> <span class="cn">FALSE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span>
<span id="cb394-6"><a href="general-statistics.html#cb394-6" tabindex="-1"></a></span>
<span id="cb394-7"><a href="general-statistics.html#cb394-7" tabindex="-1"></a>ttest_result</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  df$March.Average.Temperature..Northeast. and df$March.Average.Temperature
## t = -21.288, df = 227.4, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -10.193516  -8.466321
## sample estimates:
## mean of x mean of y 
##  32.36748  41.69740</code></pre>
<p>The p-value is less than 0.05, therefore the null hypothesis is rejected. It is concluded that there is significant difference between the North East Average Temperature for March and overall Average daily Temperature for March</p>
<ul>
<li>Perform ANOVA between the presence of Punxsutawney Phil and the February average temperature</li>
</ul>
<p>Formulate the hypothesis</p>
<ul>
<li>Null Hypothesis(<span class="math inline">\(H_0\)</span>): There is no significant difference between the presence and the absence of Punxsutawney Phil during February based on the Average Temperature</li>
<li>Alternate Hypothesis(<span class="math inline">\(H_a\)</span>): There is a significant difference between the presence and the absence of Punxsutawney Phil during February based on the Average Temperature</li>
</ul>
<div class="sourceCode" id="cb396"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb396-1"><a href="general-statistics.html#cb396-1" tabindex="-1"></a><span class="co"># Perform ANOVA</span></span>
<span id="cb396-2"><a href="general-statistics.html#cb396-2" tabindex="-1"></a>anova_result <span class="ot">&lt;-</span> <span class="fu">aov</span>(February.Average.Temperature <span class="sc">~</span> df<span class="sc">$</span>Punxsutawney.Phil, <span class="at">data =</span> df)</span>
<span id="cb396-3"><a href="general-statistics.html#cb396-3" tabindex="-1"></a></span>
<span id="cb396-4"><a href="general-statistics.html#cb396-4" tabindex="-1"></a><span class="co"># Display the ANOVA table</span></span>
<span id="cb396-5"><a href="general-statistics.html#cb396-5" tabindex="-1"></a><span class="fu">summary</span>(anova_result)</span></code></pre></div>
<pre><code>##                       Df Sum Sq Mean Sq F value Pr(&gt;F)  
## df$Punxsutawney.Phil   4   92.7   23.18   2.258 0.0669 .
## Residuals            118 1211.3   10.27                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 9 observations deleted due to missingness</code></pre>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="group-manipulation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="simple-linear-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/balsaedi/RCourse/edit/main/04-general_statistics.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/balsaedi/RCourse/blob/main/04-general_statistics.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
