<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Simple Linear Regression | Statistical Computing</title>
  <meta name="description" content="Chapter 5 Simple Linear Regression | Statistical Computing" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Simple Linear Regression | Statistical Computing" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Simple Linear Regression | Statistical Computing" />
  
  
  

<meta name="author" content="Basim Alsaedi" />


<meta name="date" content="2025-02-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="general-statistics.html"/>
<link rel="next" href="reproducibility-and-report-with-r-markdown.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">SHORT TITLE HERE</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Reviews</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#data-types-and-structures"><i class="fa fa-check"></i><b>1.1</b> Data Types and Structures</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#data-types"><i class="fa fa-check"></i><b>1.1.1</b> Data Types</a></li>
<li class="chapter" data-level="1.1.2" data-path="index.html"><a href="index.html#data-structures"><i class="fa fa-check"></i><b>1.1.2</b> Data Structures</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#data-importing-and-exporting"><i class="fa fa-check"></i><b>1.2</b> Data Importing and Exporting</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#data-cleaning"><i class="fa fa-check"></i><b>1.3</b> Data Cleaning</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#data-visualization"><i class="fa fa-check"></i><b>1.4</b> Data Visualization</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#hands-on-exercises"><i class="fa fa-check"></i><b>1.5</b> <span style="color: green;"><strong>Hands-on Exercises</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>2</b> Functions</a>
<ul>
<li class="chapter" data-level="2.1" data-path="functions.html"><a href="functions.html#writing-functions"><i class="fa fa-check"></i><b>2.1</b> Writing Functions</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="functions.html"><a href="functions.html#user-defined-functions"><i class="fa fa-check"></i><b>2.1.1</b> User-Defined Functions</a></li>
<li class="chapter" data-level="2.1.2" data-path="functions.html"><a href="functions.html#built-in-fuctions"><i class="fa fa-check"></i><b>2.1.2</b> Built-in Fuctions</a></li>
<li class="chapter" data-level="2.1.3" data-path="functions.html"><a href="functions.html#package-functions"><i class="fa fa-check"></i><b>2.1.3</b> Package Functions</a></li>
<li class="chapter" data-level="2.1.4" data-path="functions.html"><a href="functions.html#type-of-arguments-in-r-functions"><i class="fa fa-check"></i><b>2.1.4</b> Type of arguments in R functions</a></li>
<li class="chapter" data-level="2.1.5" data-path="functions.html"><a href="functions.html#understanding-return-values-in-r-functions"><i class="fa fa-check"></i><b>2.1.5</b> Understanding Return Values in R Functions</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="functions.html"><a href="functions.html#calling-the-functions"><i class="fa fa-check"></i><b>2.2</b> Calling the Functions</a></li>
<li class="chapter" data-level="2.3" data-path="functions.html"><a href="functions.html#function-documentation"><i class="fa fa-check"></i><b>2.3</b> Function Documentation</a></li>
<li class="chapter" data-level="2.4" data-path="functions.html"><a href="functions.html#hands-on-exercise"><i class="fa fa-check"></i><b>2.4</b> <span style="color: green;"><strong>Hands-on Exercise</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="group-manipulation.html"><a href="group-manipulation.html"><i class="fa fa-check"></i><b>3</b> Group Manipulation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="group-manipulation.html"><a href="group-manipulation.html#apply-family"><i class="fa fa-check"></i><b>3.1</b> Apply Family</a></li>
<li class="chapter" data-level="3.2" data-path="group-manipulation.html"><a href="group-manipulation.html#aggregate-plyr"><i class="fa fa-check"></i><b>3.2</b> Aggregate Plyr</a></li>
<li class="chapter" data-level="3.3" data-path="group-manipulation.html"><a href="group-manipulation.html#data-reshaping"><i class="fa fa-check"></i><b>3.3</b> Data Reshaping</a></li>
<li class="chapter" data-level="3.4" data-path="group-manipulation.html"><a href="group-manipulation.html#hands-on-exercise-1"><i class="fa fa-check"></i><b>3.4</b> <span style="color: green;"><strong>Hands-on Exercise</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="general-statistics.html"><a href="general-statistics.html"><i class="fa fa-check"></i><b>4</b> General Statistics</a>
<ul>
<li class="chapter" data-level="4.1" data-path="general-statistics.html"><a href="general-statistics.html#measure-of-spread-and-central-tendency"><i class="fa fa-check"></i><b>4.1</b> Measure of Spread and Central Tendency</a></li>
<li class="chapter" data-level="4.2" data-path="general-statistics.html"><a href="general-statistics.html#data-visualization-1"><i class="fa fa-check"></i><b>4.2</b> Data Visualization</a></li>
<li class="chapter" data-level="4.3" data-path="general-statistics.html"><a href="general-statistics.html#inferential-statistics"><i class="fa fa-check"></i><b>4.3</b> Inferential Statistics</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="general-statistics.html"><a href="general-statistics.html#introduction-to-hypothesis-testing"><i class="fa fa-check"></i><b>4.3.1</b> Introduction to Hypothesis Testing</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="general-statistics.html"><a href="general-statistics.html#hands-on-exercise-2"><i class="fa fa-check"></i><b>4.4</b> <span style="color: green;"><strong>Hands-on Exercise</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html"><i class="fa fa-check"></i><b>5</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="5.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#basics-of-wilkinson-rogers-notation-y-x-linear-regression"><i class="fa fa-check"></i><b>5.1</b> Basics of Wilkinson-Rogers Notation (y ~ x), Linear Regression</a></li>
<li class="chapter" data-level="5.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#scatterplots-with-regression-lines-reading-lm-output"><i class="fa fa-check"></i><b>5.2</b> Scatterplots with Regression Lines, Reading lm() Output</a></li>
<li class="chapter" data-level="5.3" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#confidence-intervals-for-regression-coefficients-testing-coefficients"><i class="fa fa-check"></i><b>5.3</b> Confidence Intervals for Regression Coefficients, Testing Coefficients</a></li>
<li class="chapter" data-level="5.4" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#tests-on-the-regression-coefficients"><i class="fa fa-check"></i><b>5.4</b> Tests on the Regression Coefficients</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#why-test-regression-coefficients"><i class="fa fa-check"></i><b>5.4.1</b> Why Test Regression Coefficients?</a></li>
<li class="chapter" data-level="5.4.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#hypothesis-testing-for-regression-coefficients"><i class="fa fa-check"></i><b>5.4.2</b> Hypothesis Testing for Regression Coefficients</a></li>
<li class="chapter" data-level="5.4.3" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#confidence-intervals-for-regression-coefficients"><i class="fa fa-check"></i><b>5.4.3</b> Confidence Intervals for Regression Coefficients</a></li>
<li class="chapter" data-level="5.4.4" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#visualizing-regression-line-and-confidence-intervals"><i class="fa fa-check"></i><b>5.4.4</b> Visualizing Regression Line and Confidence Intervals</a></li>
<li class="chapter" data-level="5.4.5" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#testing-individual-coefficients-using-car-package"><i class="fa fa-check"></i><b>5.4.5</b> Testing Individual Coefficients Using <code>car</code> Package</a></li>
<li class="chapter" data-level="5.4.6" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#practical-exercises"><i class="fa fa-check"></i><b>5.4.6</b> Practical Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#identifying-points-in-a-plot"><i class="fa fa-check"></i><b>5.5</b> Identifying Points in a Plot</a></li>
<li class="chapter" data-level="5.6" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#hands-on-exercise-3"><i class="fa fa-check"></i><b>5.6</b> <span style="color: green;"><strong>Hands-On Exercise</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="reproducibility-and-report-with-r-markdown.html"><a href="reproducibility-and-report-with-r-markdown.html"><i class="fa fa-check"></i><b>6</b> Reproducibility and Report with R Markdown</a>
<ul>
<li class="chapter" data-level="6.1" data-path="reproducibility-and-report-with-r-markdown.html"><a href="reproducibility-and-report-with-r-markdown.html#key-tools-in-r-for-reproducibility-and-reporting"><i class="fa fa-check"></i><b>6.1</b> Key Tools in R for Reproducibility and Reporting</a></li>
<li class="chapter" data-level="6.2" data-path="reproducibility-and-report-with-r-markdown.html"><a href="reproducibility-and-report-with-r-markdown.html#creating-reproducible-reports"><i class="fa fa-check"></i><b>6.2</b> Creating Reproducible Reports</a></li>
<li class="chapter" data-level="6.3" data-path="reproducibility-and-report-with-r-markdown.html"><a href="reproducibility-and-report-with-r-markdown.html#going-beyond-shiny-for-interactive-reporting"><i class="fa fa-check"></i><b>6.3</b> Going Beyond: Shiny for Interactive Reporting</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="r-shiny.html"><a href="r-shiny.html"><i class="fa fa-check"></i><b>7</b> R Shiny</a>
<ul>
<li class="chapter" data-level="7.1" data-path="r-shiny.html"><a href="r-shiny.html#structure-of-a-shiny-app"><i class="fa fa-check"></i><b>7.1</b> Structure of a Shiny App</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="r-shiny.html"><a href="r-shiny.html#user-interfaceui"><i class="fa fa-check"></i><b>7.1.1</b> User Interface(ui)</a></li>
<li class="chapter" data-level="7.1.2" data-path="r-shiny.html"><a href="r-shiny.html#server"><i class="fa fa-check"></i><b>7.1.2</b> Server</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="r-shiny.html"><a href="r-shiny.html#hands-on-exercise-4"><i class="fa fa-check"></i><b>7.2</b> <span style="color: green;"><strong>Hands-On Exercise</strong></span></a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="building-r-packages.html"><a href="building-r-packages.html"><i class="fa fa-check"></i><b>8</b> Building R Packages</a>
<ul>
<li class="chapter" data-level="8.1" data-path="building-r-packages.html"><a href="building-r-packages.html#introduction"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="building-r-packages.html"><a href="building-r-packages.html#prerequisites"><i class="fa fa-check"></i><b>8.2</b> Prerequisites</a></li>
<li class="chapter" data-level="8.3" data-path="building-r-packages.html"><a href="building-r-packages.html#building-a-simple-r-package"><i class="fa fa-check"></i><b>8.3</b> Building a simple R package</a></li>
<li class="chapter" data-level="8.4" data-path="building-r-packages.html"><a href="building-r-packages.html#making-a-new-r-project"><i class="fa fa-check"></i><b>8.4</b> Making A New R Project</a></li>
<li class="chapter" data-level="8.5" data-path="building-r-packages.html"><a href="building-r-packages.html#adding-documentation"><i class="fa fa-check"></i><b>8.5</b> Adding Documentation</a></li>
<li class="chapter" data-level="8.6" data-path="building-r-packages.html"><a href="building-r-packages.html#uploading-and-installing-from-github"><i class="fa fa-check"></i><b>8.6</b> Uploading and Installing from Github</a></li>
<li class="chapter" data-level="8.7" data-path="building-r-packages.html"><a href="building-r-packages.html#hands-on-exercises-1"><i class="fa fa-check"></i><b>8.7</b> <span style="color: green;"><strong>Hands-on Exercises</strong></span></a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Computing</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="simple-linear-regression" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Chapter 5</span> Simple Linear Regression<a href="simple-linear-regression.html#simple-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Welcome to the world of Simple Linear Regression! 🎉 This statistical technique is super handy when you want to explore the relationship between two continuous variables. Essentially, it helps us predict the value of one variable based on the value of another.</p>
<p>For example, imagine you want to predict a student’s exam score based on the number of hours they studied. Here, the hours studied are the <strong>independent variable</strong> (or predictor), and the exam score is the <strong>dependent variable</strong> (or response).</p>
<p><strong>What is Simple Linear Regression?</strong></p>
<p>Simple linear regression is essentially about finding the line that best describes the relationship between two variables(independent and dependent variables) in your data. The line is called the <strong>regression line</strong>, and it helps us make predictions.</p>
<div id="basics-of-wilkinson-rogers-notation-y-x-linear-regression" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Basics of Wilkinson-Rogers Notation (y ~ x), Linear Regression<a href="simple-linear-regression.html#basics-of-wilkinson-rogers-notation-y-x-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In simple linear regression, we fit a straight line (called the regression line) through the data points. This line is defined by the equation:</p>
<p><span class="math display">\[y = mx + b\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(y\)</span> is the predicted value (dependent variable).</li>
<li><span class="math inline">\(m\)</span> is the slope of the line (how much <span class="math inline">\(y\)</span> changes for a unit change in <span class="math inline">\(x\)</span>).</li>
<li><span class="math inline">\(x\)</span> is the independent variable.</li>
<li><span class="math inline">\(b\)</span> is the y-intercept (the value of <span class="math inline">\(y\)</span> when <span class="math inline">\(x\)</span> is 0).</li>
</ul>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>Lets say, we have a data set of age and height of youngsters as below here:</p>
<pre><code>age = c(5, 10, 15, 20, 25)
height = c(110, 130, 150, 160, 170)</code></pre>
<p>We can use the age to predict the height where age is the independent variable and height is the dependent variable(depends on age). The equation is written like this in R;</p>
<pre><code>height ~ age</code></pre>
<p>in short <code>independent_variable ~ dependent_variable</code>. Now, lets work it out using the <code>lm()</code> function</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="simple-linear-regression.html#cb3-1" tabindex="-1"></a><span class="co"># Creating a sample data set</span></span>
<span id="cb3-2"><a href="simple-linear-regression.html#cb3-2" tabindex="-1"></a>age <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">20</span>, <span class="dv">25</span>)</span>
<span id="cb3-3"><a href="simple-linear-regression.html#cb3-3" tabindex="-1"></a>height <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">110</span>, <span class="dv">130</span>, <span class="dv">150</span>, <span class="dv">160</span>, <span class="dv">170</span>)</span>
<span id="cb3-4"><a href="simple-linear-regression.html#cb3-4" tabindex="-1"></a></span>
<span id="cb3-5"><a href="simple-linear-regression.html#cb3-5" tabindex="-1"></a><span class="co"># Fitting a linear regression data set</span></span>
<span id="cb3-6"><a href="simple-linear-regression.html#cb3-6" tabindex="-1"></a>model_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(height <span class="sc">~</span> age)</span></code></pre></div>
<p>The <code>lm()</code> function stands for ’linear model` and it finds the best line to describle the relationship between height and age.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="simple-linear-regression.html#cb4-1" tabindex="-1"></a><span class="fu">summary</span>(model_1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = height ~ age)
## 
## Residuals:
##  1  2  3  4  5 
## -4  1  6  1 -4 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  99.0000     5.0662   19.54 0.000293 ***
## age           3.0000     0.3055    9.82 0.002245 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.83 on 3 degrees of freedom
## Multiple R-squared:  0.9698, Adjusted R-squared:  0.9598 
## F-statistic: 96.43 on 1 and 3 DF,  p-value: 0.002245</code></pre>
<p><span style="color: orange;"><strong>Real world challenge</strong></span></p>
<p>Let’s use the built-in <code>mtcars</code> data set in R to demonstrate how to perform simple linear regression.</p>
<p>Load the data set</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="simple-linear-regression.html#cb6-1" tabindex="-1"></a><span class="co"># Load the mtcars dataset</span></span>
<span id="cb6-2"><a href="simple-linear-regression.html#cb6-2" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span>
<span id="cb6-3"><a href="simple-linear-regression.html#cb6-3" tabindex="-1"></a><span class="co"># View the first few rows of the dataset</span></span>
<span id="cb6-4"><a href="simple-linear-regression.html#cb6-4" tabindex="-1"></a><span class="fu">head</span>(mtcars)</span></code></pre></div>
<pre><code>##                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
## Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
## Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1</code></pre>
<p>Fit the simple linear regression model that will predict <code>mpg</code> (miles per gallon) based on <code>wt</code> (the weight of the car).</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="simple-linear-regression.html#cb8-1" tabindex="-1"></a><span class="co"># Fit the linear regression model</span></span>
<span id="cb8-2"><a href="simple-linear-regression.html#cb8-2" tabindex="-1"></a>model_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> wt, <span class="at">data =</span> mtcars)</span></code></pre></div>
<ul>
<li>Get the model summary to get important information about the model we just fitted.</li>
</ul>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="simple-linear-regression.html#cb9-1" tabindex="-1"></a><span class="co"># Get the summary of the model</span></span>
<span id="cb9-2"><a href="simple-linear-regression.html#cb9-2" tabindex="-1"></a><span class="fu">summary</span>(model_2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ wt, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.5432 -2.3647 -0.1252  1.4096  6.8727 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  37.2851     1.8776  19.858  &lt; 2e-16 ***
## wt           -5.3445     0.5591  -9.559 1.29e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.046 on 30 degrees of freedom
## Multiple R-squared:  0.7528, Adjusted R-squared:  0.7446 
## F-statistic: 91.38 on 1 and 30 DF,  p-value: 1.294e-10</code></pre>
</div>
<div id="scatterplots-with-regression-lines-reading-lm-output" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Scatterplots with Regression Lines, Reading lm() Output<a href="simple-linear-regression.html#scatterplots-with-regression-lines-reading-lm-output" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now that we have a model in place lets plot the data and regression line to understand the relationship. You remember we have just worked on a case of where we use the age of youngsters to find their height? That’s fine! Lets plot a scatter plot and regression line to visualize the relationship between age and height.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="simple-linear-regression.html#cb11-1" tabindex="-1"></a><span class="co"># Scatter plot of age vs height </span></span>
<span id="cb11-2"><a href="simple-linear-regression.html#cb11-2" tabindex="-1"></a><span class="fu">plot</span>(age, height,</span>
<span id="cb11-3"><a href="simple-linear-regression.html#cb11-3" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Height vs Age&quot;</span>, </span>
<span id="cb11-4"><a href="simple-linear-regression.html#cb11-4" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Age&quot;</span>,</span>
<span id="cb11-5"><a href="simple-linear-regression.html#cb11-5" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Height&quot;</span>,<span class="at">pch=</span><span class="dv">19</span>,</span>
<span id="cb11-6"><a href="simple-linear-regression.html#cb11-6" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">&quot;blue&quot;</span></span>
<span id="cb11-7"><a href="simple-linear-regression.html#cb11-7" tabindex="-1"></a>       )</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>The scatter plot shows that the youngsters tend to be taller as they get older. Now lets add a regression line to the data to see how well it fits the data;</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="simple-linear-regression.html#cb12-1" tabindex="-1"></a><span class="co"># Scatter plot of age vs height </span></span>
<span id="cb12-2"><a href="simple-linear-regression.html#cb12-2" tabindex="-1"></a><span class="fu">plot</span>(age, height,</span>
<span id="cb12-3"><a href="simple-linear-regression.html#cb12-3" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Height vs Age&quot;</span>, </span>
<span id="cb12-4"><a href="simple-linear-regression.html#cb12-4" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Age&quot;</span>,</span>
<span id="cb12-5"><a href="simple-linear-regression.html#cb12-5" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Height&quot;</span>,<span class="at">pch=</span><span class="dv">19</span>,</span>
<span id="cb12-6"><a href="simple-linear-regression.html#cb12-6" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">&quot;blue&quot;</span></span>
<span id="cb12-7"><a href="simple-linear-regression.html#cb12-7" tabindex="-1"></a>       )</span>
<span id="cb12-8"><a href="simple-linear-regression.html#cb12-8" tabindex="-1"></a></span>
<span id="cb12-9"><a href="simple-linear-regression.html#cb12-9" tabindex="-1"></a><span class="co"># Adding a regression line </span></span>
<span id="cb12-10"><a href="simple-linear-regression.html#cb12-10" tabindex="-1"></a><span class="fu">abline</span>(model_1, <span class="at">col=</span><span class="st">&quot;red&quot;</span>, <span class="at">lwd=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>The regression line helps us visually understand the trend. In our case here, the regression line closely follows the data points, therefore, our model is a good fit!</p>
<p><span style="color: orange;"><strong>Real World example</strong></span></p>
<p>We will still consider the model that we created above for the <code>mtcars</code> data set. Lets plot a scatter plot and fit a regression line based on the model that we have just created.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="simple-linear-regression.html#cb13-1" tabindex="-1"></a><span class="co"># Plot the data points</span></span>
<span id="cb13-2"><a href="simple-linear-regression.html#cb13-2" tabindex="-1"></a><span class="fu">plot</span>(mtcars<span class="sc">$</span>wt, mtcars<span class="sc">$</span>mpg, </span>
<span id="cb13-3"><a href="simple-linear-regression.html#cb13-3" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Simple Linear Regression&quot;</span>, </span>
<span id="cb13-4"><a href="simple-linear-regression.html#cb13-4" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Weight of the Car (wt)&quot;</span>, </span>
<span id="cb13-5"><a href="simple-linear-regression.html#cb13-5" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Miles Per Gallon (mpg)&quot;</span>, </span>
<span id="cb13-6"><a href="simple-linear-regression.html#cb13-6" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span>
<span id="cb13-7"><a href="simple-linear-regression.html#cb13-7" tabindex="-1"></a></span>
<span id="cb13-8"><a href="simple-linear-regression.html#cb13-8" tabindex="-1"></a><span class="co"># Add the regression line</span></span>
<span id="cb13-9"><a href="simple-linear-regression.html#cb13-9" tabindex="-1"></a><span class="fu">abline</span>(model_2, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Predictions can be made based on the data. Lets predict the mpg for car that weighs 3.5 tons</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="simple-linear-regression.html#cb14-1" tabindex="-1"></a><span class="co"># Predict mpg for a car that weighs 3.5 tons</span></span>
<span id="cb14-2"><a href="simple-linear-regression.html#cb14-2" tabindex="-1"></a>new_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">wt =</span> <span class="fl">3.5</span>)</span>
<span id="cb14-3"><a href="simple-linear-regression.html#cb14-3" tabindex="-1"></a>predicted_mpg <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_2, new_data)</span>
<span id="cb14-4"><a href="simple-linear-regression.html#cb14-4" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;Predicted MPG for a car weighing 3.5 tons:&quot;</span>, <span class="fu">round</span>(predicted_mpg, <span class="dv">2</span>)))</span></code></pre></div>
<pre><code>## [1] &quot;Predicted MPG for a car weighing 3.5 tons: 18.58&quot;</code></pre>
</div>
<div id="confidence-intervals-for-regression-coefficients-testing-coefficients" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Confidence Intervals for Regression Coefficients, Testing Coefficients<a href="simple-linear-regression.html#confidence-intervals-for-regression-coefficients-testing-coefficients" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Lets revisit the model that we fitted age and height of youths.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="simple-linear-regression.html#cb16-1" tabindex="-1"></a><span class="fu">summary</span>(model_1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = height ~ age)
## 
## Residuals:
##  1  2  3  4  5 
## -4  1  6  1 -4 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  99.0000     5.0662   19.54 0.000293 ***
## age           3.0000     0.3055    9.82 0.002245 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.83 on 3 degrees of freedom
## Multiple R-squared:  0.9698, Adjusted R-squared:  0.9598 
## F-statistic: 96.43 on 1 and 3 DF,  p-value: 0.002245</code></pre>
<p>Here we will focus on the coefficients and the confidence intervals. The confidence interval for each regression coefficient helps us understand the range within which true value of the coeefficient is likely to fall.</p>
<p>The <code>confint()</code> function in R is used to obtain this information.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="simple-linear-regression.html#cb18-1" tabindex="-1"></a><span class="co"># Calculate the confidence interval </span></span>
<span id="cb18-2"><a href="simple-linear-regression.html#cb18-2" tabindex="-1"></a><span class="fu">confint</span>(model_1)</span></code></pre></div>
<pre><code>##                 2.5 %     97.5 %
## (Intercept) 82.877001 115.122999
## age          2.027747   3.972253</code></pre>
<p>As stated earlier the simple linear regression model equation is <span class="math inline">\(y = mx + b\)</span>; we will remodel this equation to fit the 2.5% and 97.5% confidence interval inform of <span class="math inline">\(height(y) = Coefficient(m) * age(x) + Intercept(b)\)</span>. Therefore:</p>
<ul>
<li>At 2.5% confidence interval; the equation is <span class="math display">\[height  = 2.028 * age + 82.877\]</span></li>
<li>At 97.5% confidence interval; the equations is <span class="math display">\[height  = 3.972 * age + 115.123\]</span></li>
</ul>
<p>Using the equations above you can estimate the height of the youth based on age.</p>
</div>
<div id="tests-on-the-regression-coefficients" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> Tests on the Regression Coefficients<a href="simple-linear-regression.html#tests-on-the-regression-coefficients" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In simple linear regression, we estimate a model of the form:</p>
<p><span class="math display">\[
    Y = \beta_0 + \beta_1 X + \epsilon
    \]</span></p>
<p>where:</p>
<ul>
<li><p><span class="math inline">\(\beta_0\)</span> (intercept) and <span class="math inline">\(\beta_1\)</span> (slope) are the regression coefficients.</p></li>
<li><p><span class="math inline">\(X\)</span> is the independent variable.</p></li>
<li><p><span class="math inline">\(Y\)</span> is the dependent variable.</p></li>
<li><p><span class="math inline">\(\epsilon\)</span> is the random error.</p></li>
</ul>
<div id="why-test-regression-coefficients" class="section level3 hasAnchor" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> Why Test Regression Coefficients?<a href="simple-linear-regression.html#why-test-regression-coefficients" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>To determine if the <strong>slope (<span class="math inline">\(\beta_1\)</span>)</strong> significantly differs from zero.</p></li>
<li><p>To check if the <strong>intercept (<span class="math inline">\(\beta_0\)</span>)</strong> is significant.</p></li>
<li><p>To assess whether the independent variable <strong>significantly predicts</strong> the dependent variable.</p></li>
</ul>
<hr />
</div>
<div id="hypothesis-testing-for-regression-coefficients" class="section level3 hasAnchor" number="5.4.2">
<h3><span class="header-section-number">5.4.2</span> Hypothesis Testing for Regression Coefficients<a href="simple-linear-regression.html#hypothesis-testing-for-regression-coefficients" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <strong>t-test</strong> is used to test the significance of the regression coefficients.</p>
<div id="null-and-alternative-hypotheses" class="section level4 hasAnchor" number="5.4.2.1">
<h4><span class="header-section-number">5.4.2.1</span> Null and Alternative Hypotheses<a href="simple-linear-regression.html#null-and-alternative-hypotheses" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>For the <strong>intercept</strong> (<span class="math inline">\(\beta_0\)</span>):
<span class="math display">\[
    H_0: \beta_0 = 0 \quad \text{(No significant intercept)}
    \]</span>
<span class="math display">\[
  H_A: \beta_0 \neq 0 \quad \text{(Intercept is significant)}
  \]</span></p>
<p>For the <strong>slope</strong> (<span class="math inline">\(\beta_1\)</span>):
<span class="math display">\[
    H_0: \beta_1 = 0 \quad \text{(No relationship between \(X\) and \(Y\))}
    \]</span>
<span class="math display">\[
  H_A: \beta_1 \neq 0 \quad \text{(Significant relationship)}
  \]</span></p>
<hr />
</div>
<div id="example-predicting-sales-from-advertising-budget" class="section level4 hasAnchor" number="5.4.2.2">
<h4><span class="header-section-number">5.4.2.2</span> Example: Predicting Sales from Advertising Budget<a href="simple-linear-regression.html#example-predicting-sales-from-advertising-budget" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="simple-linear-regression.html#cb20-1" tabindex="-1"></a><span class="co"># Load necessary library</span></span>
<span id="cb20-2"><a href="simple-linear-regression.html#cb20-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div>
<pre><code>## Warning: package &#39;ggplot2&#39; was built under R version 4.3.3</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="simple-linear-regression.html#cb22-1" tabindex="-1"></a><span class="co"># Sample data</span></span>
<span id="cb22-2"><a href="simple-linear-regression.html#cb22-2" tabindex="-1"></a>advertising <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">20</span>, <span class="dv">25</span>, <span class="dv">30</span>, <span class="dv">35</span>, <span class="dv">40</span>, <span class="dv">45</span>, <span class="dv">50</span>, <span class="dv">55</span>)</span>
<span id="cb22-3"><a href="simple-linear-regression.html#cb22-3" tabindex="-1"></a>sales <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">16</span>, <span class="dv">18</span>, <span class="dv">22</span>, <span class="dv">25</span>, <span class="dv">28</span>)</span>
<span id="cb22-4"><a href="simple-linear-regression.html#cb22-4" tabindex="-1"></a></span>
<span id="cb22-5"><a href="simple-linear-regression.html#cb22-5" tabindex="-1"></a><span class="co"># Fit the linear regression model</span></span>
<span id="cb22-6"><a href="simple-linear-regression.html#cb22-6" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(sales <span class="sc">~</span> advertising)</span>
<span id="cb22-7"><a href="simple-linear-regression.html#cb22-7" tabindex="-1"></a></span>
<span id="cb22-8"><a href="simple-linear-regression.html#cb22-8" tabindex="-1"></a><span class="co"># Display summary</span></span>
<span id="cb22-9"><a href="simple-linear-regression.html#cb22-9" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sales ~ advertising)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.5091 -0.8606  0.3182  0.8424  1.2727 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1.46061    0.84342  -1.732    0.122    
## advertising  0.51879    0.02374  21.856 2.03e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.078 on 8 degrees of freedom
## Multiple R-squared:  0.9835, Adjusted R-squared:  0.9815 
## F-statistic: 477.7 on 1 and 8 DF,  p-value: 2.027e-08</code></pre>
<hr />
<p><strong>Interpreting Regression Output</strong></p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="simple-linear-regression.html#cb24-1" tabindex="-1"></a><span class="fu">summary</span>(model)<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>##               Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept) -1.4606061 0.84342104 -1.731764 1.215559e-01
## advertising  0.5187879 0.02373716 21.855517 2.026551e-08</code></pre>
<ul>
<li><p><strong>Intercept (<span class="math inline">\(\beta_0\)</span>):</strong> Not significant (p = 0.121), meaning the model does not strongly support an inherent baseline sales value.</p></li>
<li><p><strong>Slope (<span class="math inline">\(\beta_1\)</span>):</strong> Highly significant (p = 0.00000002026551), meaning <strong>advertising budget significantly predicts sales</strong>.</p></li>
</ul>
<hr />
</div>
</div>
<div id="confidence-intervals-for-regression-coefficients" class="section level3 hasAnchor" number="5.4.3">
<h3><span class="header-section-number">5.4.3</span> Confidence Intervals for Regression Coefficients<a href="simple-linear-regression.html#confidence-intervals-for-regression-coefficients" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can compute <strong>confidence intervals</strong> for regression coefficients.</p>
<div id="example-95-confidence-intervals" class="section level4 hasAnchor" number="5.4.3.1">
<h4><span class="header-section-number">5.4.3.1</span> Example: 95% Confidence Intervals<a href="simple-linear-regression.html#example-95-confidence-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="simple-linear-regression.html#cb26-1" tabindex="-1"></a><span class="fu">confint</span>(model, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>##                  2.5 %    97.5 %
## (Intercept) -3.4055385 0.4843263
## advertising  0.4640499 0.5735259</code></pre>
<ul>
<li>If the confidence interval for <span class="math inline">\(\beta_1\)</span> does not include <strong>zero</strong>, the predictor is significant.</li>
</ul>
<hr />
</div>
</div>
<div id="visualizing-regression-line-and-confidence-intervals" class="section level3 hasAnchor" number="5.4.4">
<h3><span class="header-section-number">5.4.4</span> Visualizing Regression Line and Confidence Intervals<a href="simple-linear-regression.html#visualizing-regression-line-and-confidence-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="example-scatterplot-with-regression-line" class="section level4 hasAnchor" number="5.4.4.1">
<h4><span class="header-section-number">5.4.4.1</span> Example: Scatterplot with Regression Line<a href="simple-linear-regression.html#example-scatterplot-with-regression-line" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="simple-linear-regression.html#cb28-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(advertising, sales), <span class="fu">aes</span>(<span class="at">x =</span> advertising, <span class="at">y =</span> sales)) <span class="sc">+</span></span>
<span id="cb28-2"><a href="simple-linear-regression.html#cb28-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb28-3"><a href="simple-linear-regression.html#cb28-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb28-4"><a href="simple-linear-regression.html#cb28-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Sales vs Advertising Budget&quot;</span>,</span>
<span id="cb28-5"><a href="simple-linear-regression.html#cb28-5" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Advertising Budget&quot;</span>,</span>
<span id="cb28-6"><a href="simple-linear-regression.html#cb28-6" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Sales&quot;</span>) <span class="sc">+</span></span>
<span id="cb28-7"><a href="simple-linear-regression.html#cb28-7" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<hr />
</div>
</div>
<div id="testing-individual-coefficients-using-car-package" class="section level3 hasAnchor" number="5.4.5">
<h3><span class="header-section-number">5.4.5</span> Testing Individual Coefficients Using <code>car</code> Package<a href="simple-linear-regression.html#testing-individual-coefficients-using-car-package" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <code>car</code> package provides robust significance tests.</p>
<div id="example-linearhypothesis-for-testing-beta_1" class="section level4 hasAnchor" number="5.4.5.1">
<h4><span class="header-section-number">5.4.5.1</span> Example: <code>linearHypothesis()</code> for Testing <span class="math inline">\(\beta_1\)</span><a href="simple-linear-regression.html#example-linearhypothesis-for-testing-beta_1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="simple-linear-regression.html#cb30-1" tabindex="-1"></a><span class="fu">library</span>(car)</span></code></pre></div>
<pre><code>## Warning: package &#39;car&#39; was built under R version 4.3.3</code></pre>
<pre><code>## Loading required package: carData</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="simple-linear-regression.html#cb33-1" tabindex="-1"></a><span class="fu">linearHypothesis</span>(model, <span class="st">&quot;advertising = 0&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Linear hypothesis test:
## advertising = 0
## 
## Model 1: restricted model
## Model 2: sales ~ advertising
## 
##   Res.Df   RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1      9 564.4                                  
## 2      8   9.3  1     555.1 477.66 2.027e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<ul>
<li>If <strong>p-value &lt; 0.05</strong>, we reject <span class="math inline">\(H_0\)</span>, meaning <strong>advertising has a significant effect</strong> on sales.</li>
</ul>
<hr />
</div>
</div>
<div id="practical-exercises" class="section level3 hasAnchor" number="5.4.6">
<h3><span class="header-section-number">5.4.6</span> Practical Exercises<a href="simple-linear-regression.html#practical-exercises" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="exercise-1-running-a-regression-model" class="section level4 hasAnchor" number="5.4.6.1">
<h4><span class="header-section-number">5.4.6.1</span> Exercise 1: Running a Regression Model<a href="simple-linear-regression.html#exercise-1-running-a-regression-model" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ol style="list-style-type: decimal">
<li>Use the dataset:</li>
</ol>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="simple-linear-regression.html#cb35-1" tabindex="-1"></a>experience <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">10</span>)</span>
<span id="cb35-2"><a href="simple-linear-regression.html#cb35-2" tabindex="-1"></a>salary <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">40000</span>, <span class="dv">42000</span>, <span class="dv">45000</span>, <span class="dv">47000</span>, <span class="dv">50000</span>, <span class="dv">52000</span>, <span class="dv">55000</span>, <span class="dv">58000</span>, <span class="dv">60000</span>, <span class="dv">63000</span>)</span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li><p>Fit a <strong>linear regression model</strong> predicting salary from experience.</p></li>
<li><p>Perform hypothesis tests on <strong>coefficients</strong>.</p></li>
</ol>
<p><strong>Solution</strong></p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="simple-linear-regression.html#cb36-1" tabindex="-1"></a>salary_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> experience)</span>
<span id="cb36-2"><a href="simple-linear-regression.html#cb36-2" tabindex="-1"></a><span class="fu">summary</span>(salary_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = salary ~ experience)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -484.85 -203.03   15.15  233.33  375.76 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 37066.67     219.27  169.04 1.68e-15 ***
## experience   2569.70      35.34   72.72 1.43e-12 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 321 on 8 degrees of freedom
## Multiple R-squared:  0.9985, Adjusted R-squared:  0.9983 
## F-statistic:  5288 on 1 and 8 DF,  p-value: 1.425e-12</code></pre>
<hr />
</div>
<div id="exercise-2-computing-confidence-intervals" class="section level4 hasAnchor" number="5.4.6.2">
<h4><span class="header-section-number">5.4.6.2</span> Exercise 2: Computing Confidence Intervals<a href="simple-linear-regression.html#exercise-2-computing-confidence-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ol style="list-style-type: decimal">
<li><p>Use the <strong>same dataset</strong> as Exercise 1.</p></li>
<li><p>Compute <strong>95% confidence intervals</strong> for regression coefficients.</p></li>
</ol>
<p><strong>Solution</strong></p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="simple-linear-regression.html#cb38-1" tabindex="-1"></a><span class="fu">confint</span>(salary_model, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>##                 2.5 %    97.5 %
## (Intercept) 36561.021 37572.312
## experience   2488.205  2651.189</code></pre>
<hr />
</div>
<div id="exercise-3-testing-significance-of-coefficients" class="section level4 hasAnchor" number="5.4.6.3">
<h4><span class="header-section-number">5.4.6.3</span> Exercise 3: Testing Significance of Coefficients<a href="simple-linear-regression.html#exercise-3-testing-significance-of-coefficients" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ol style="list-style-type: decimal">
<li><p>Use the <strong>same dataset</strong> as Exercise 1.</p></li>
<li><p>Use the <code>car</code> package to <strong>test if experience significantly predicts salary</strong>.</p></li>
</ol>
<p><strong>Solution</strong></p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="simple-linear-regression.html#cb40-1" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb40-2"><a href="simple-linear-regression.html#cb40-2" tabindex="-1"></a><span class="fu">linearHypothesis</span>(salary_model, <span class="st">&quot;experience = 0&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Linear hypothesis test:
## experience = 0
## 
## Model 1: restricted model
## Model 2: salary ~ experience
## 
##   Res.Df       RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1      9 545600000                                  
## 2      8    824242  1 544775758 5287.5 1.425e-12 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<hr />
</div>
<div id="exercise-4-visualizing-regression-model" class="section level4 hasAnchor" number="5.4.6.4">
<h4><span class="header-section-number">5.4.6.4</span> Exercise 4: Visualizing Regression Model<a href="simple-linear-regression.html#exercise-4-visualizing-regression-model" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ol style="list-style-type: decimal">
<li><p>Use the <strong>same dataset</strong> as Exercise 1.</p></li>
<li><p>Create a <strong>scatterplot with a regression line</strong>.</p></li>
</ol>
<p><strong>Solution</strong></p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="simple-linear-regression.html#cb42-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(experience, salary), <span class="fu">aes</span>(<span class="at">x =</span> experience, <span class="at">y =</span> salary)) <span class="sc">+</span></span>
<span id="cb42-2"><a href="simple-linear-regression.html#cb42-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb42-3"><a href="simple-linear-regression.html#cb42-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb42-4"><a href="simple-linear-regression.html#cb42-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Experience vs Salary&quot;</span>,</span>
<span id="cb42-5"><a href="simple-linear-regression.html#cb42-5" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Years of Experience&quot;</span>,</span>
<span id="cb42-6"><a href="simple-linear-regression.html#cb42-6" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Salary&quot;</span>) <span class="sc">+</span></span>
<span id="cb42-7"><a href="simple-linear-regression.html#cb42-7" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<hr />
<hr />
<p><span style="color: green;"><strong>Practical Exercise</strong></span></p>
<p>In this exercise, you will be required to use the built-in R <code>mtcars</code> data set. Use the weight(<code>wt</code>) to predict the fuel consumption(<code>mpg</code>). Find the equation with the confidence interval.</p>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="simple-linear-regression.html#cb44-1" tabindex="-1"></a><span class="co"># Load the data </span></span>
<span id="cb44-2"><a href="simple-linear-regression.html#cb44-2" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span>
<span id="cb44-3"><a href="simple-linear-regression.html#cb44-3" tabindex="-1"></a></span>
<span id="cb44-4"><a href="simple-linear-regression.html#cb44-4" tabindex="-1"></a><span class="co"># Fit the linear regression model</span></span>
<span id="cb44-5"><a href="simple-linear-regression.html#cb44-5" tabindex="-1"></a>model_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> wt, <span class="at">data =</span> mtcars)</span>
<span id="cb44-6"><a href="simple-linear-regression.html#cb44-6" tabindex="-1"></a></span>
<span id="cb44-7"><a href="simple-linear-regression.html#cb44-7" tabindex="-1"></a><span class="co"># Confidence intervals </span></span>
<span id="cb44-8"><a href="simple-linear-regression.html#cb44-8" tabindex="-1"></a><span class="fu">confint</span>(model_2)</span></code></pre></div>
<pre><code>##                 2.5 %    97.5 %
## (Intercept) 33.450500 41.119753
## wt          -6.486308 -4.202635</code></pre>
<ul>
<li>At 2.5% confidence interval, the equation to find <code>mpg</code> is <span class="math display">\[mpg  = -6.486 * wt + 33.351\]</span></li>
<li>At 97.5% confidence interval, the equation to find <code>mpg</code> is <span class="math display">\[mpg  = -4.203 * wt + 41.120\]</span></li>
</ul>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>
</div>
</div>
</div>
<div id="identifying-points-in-a-plot" class="section level2 hasAnchor" number="5.5">
<h2><span class="header-section-number">5.5</span> Identifying Points in a Plot<a href="simple-linear-regression.html#identifying-points-in-a-plot" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We made the scatter plot above static. Here, we will enable any researcher to identify specific points in the chart. I will now plot the chart using <code>ggplot2</code> library.</p>
<p>Lets do it</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="simple-linear-regression.html#cb46-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb46-2"><a href="simple-linear-regression.html#cb46-2" tabindex="-1"></a></span>
<span id="cb46-3"><a href="simple-linear-regression.html#cb46-3" tabindex="-1"></a><span class="co"># Create the data set</span></span>
<span id="cb46-4"><a href="simple-linear-regression.html#cb46-4" tabindex="-1"></a>height_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb46-5"><a href="simple-linear-regression.html#cb46-5" tabindex="-1"></a>  <span class="at">age =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">20</span>, <span class="dv">25</span>),</span>
<span id="cb46-6"><a href="simple-linear-regression.html#cb46-6" tabindex="-1"></a>  <span class="at">height =</span> <span class="fu">c</span>(<span class="dv">110</span>, <span class="dv">130</span>, <span class="dv">150</span>, <span class="dv">160</span>, <span class="dv">170</span>)</span>
<span id="cb46-7"><a href="simple-linear-regression.html#cb46-7" tabindex="-1"></a>)</span>
<span id="cb46-8"><a href="simple-linear-regression.html#cb46-8" tabindex="-1"></a></span>
<span id="cb46-9"><a href="simple-linear-regression.html#cb46-9" tabindex="-1"></a><span class="co"># Plot the and label the points </span></span>
<span id="cb46-10"><a href="simple-linear-regression.html#cb46-10" tabindex="-1"></a><span class="fu">ggplot</span>(height_data, </span>
<span id="cb46-11"><a href="simple-linear-regression.html#cb46-11" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> height)) <span class="sc">+</span> </span>
<span id="cb46-12"><a href="simple-linear-regression.html#cb46-12" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">size=</span><span class="dv">3</span>) <span class="sc">+</span> <span class="co"># for scatter plot </span></span>
<span id="cb46-13"><a href="simple-linear-regression.html#cb46-13" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> <span class="co"># regression line </span></span>
<span id="cb46-14"><a href="simple-linear-regression.html#cb46-14" tabindex="-1"></a>  <span class="fu">geom_text</span>(</span>
<span id="cb46-15"><a href="simple-linear-regression.html#cb46-15" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste</span>(<span class="st">&quot;(&quot;</span>, age, <span class="st">&quot;,&quot;</span>, height, <span class="st">&quot;)&quot;</span>, <span class="at">sep=</span><span class="st">&quot;&quot;</span>)),</span>
<span id="cb46-16"><a href="simple-linear-regression.html#cb46-16" tabindex="-1"></a>    <span class="at">vjust =</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">color =</span> <span class="st">&quot;darkgreen&quot;</span>) <span class="sc">+</span> <span class="co"># For interactiveness </span></span>
<span id="cb46-17"><a href="simple-linear-regression.html#cb46-17" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb46-18"><a href="simple-linear-regression.html#cb46-18" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Age vs Height with Identified points&quot;</span>, </span>
<span id="cb46-19"><a href="simple-linear-regression.html#cb46-19" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Age&quot;</span>, </span>
<span id="cb46-20"><a href="simple-linear-regression.html#cb46-20" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Height&quot;</span></span>
<span id="cb46-21"><a href="simple-linear-regression.html#cb46-21" tabindex="-1"></a>    ) <span class="sc">+</span> </span>
<span id="cb46-22"><a href="simple-linear-regression.html#cb46-22" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p><span style="color: orange;"><strong>Try it!</strong></span></p>
<p>Lets repeat the same with the mtcars data set, we will plot a weight vs fuel consumption (mpg) with identified points in the plots</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="simple-linear-regression.html#cb48-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb48-2"><a href="simple-linear-regression.html#cb48-2" tabindex="-1"></a></span>
<span id="cb48-3"><a href="simple-linear-regression.html#cb48-3" tabindex="-1"></a><span class="co"># Load the data</span></span>
<span id="cb48-4"><a href="simple-linear-regression.html#cb48-4" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span>
<span id="cb48-5"><a href="simple-linear-regression.html#cb48-5" tabindex="-1"></a></span>
<span id="cb48-6"><a href="simple-linear-regression.html#cb48-6" tabindex="-1"></a><span class="co"># Plotting</span></span>
<span id="cb48-7"><a href="simple-linear-regression.html#cb48-7" tabindex="-1"></a><span class="fu">ggplot</span>(mtcars, </span>
<span id="cb48-8"><a href="simple-linear-regression.html#cb48-8" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> wt, <span class="at">y =</span> mpg)) <span class="sc">+</span> </span>
<span id="cb48-9"><a href="simple-linear-regression.html#cb48-9" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">size=</span><span class="dv">3</span>) <span class="sc">+</span> <span class="co"># for scatter plot </span></span>
<span id="cb48-10"><a href="simple-linear-regression.html#cb48-10" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> <span class="co"># regression line </span></span>
<span id="cb48-11"><a href="simple-linear-regression.html#cb48-11" tabindex="-1"></a>  <span class="fu">geom_text</span>(</span>
<span id="cb48-12"><a href="simple-linear-regression.html#cb48-12" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste</span>(<span class="st">&quot;(&quot;</span>, wt, <span class="st">&quot;,&quot;</span>, mpg, <span class="st">&quot;)&quot;</span>, <span class="at">sep=</span><span class="st">&quot;&quot;</span>)),</span>
<span id="cb48-13"><a href="simple-linear-regression.html#cb48-13" tabindex="-1"></a>    <span class="at">vjust =</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">color =</span> <span class="st">&quot;darkgreen&quot;</span>) <span class="sc">+</span> <span class="co"># For interactiveness </span></span>
<span id="cb48-14"><a href="simple-linear-regression.html#cb48-14" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb48-15"><a href="simple-linear-regression.html#cb48-15" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Wight vs mpg with Identified points&quot;</span>, </span>
<span id="cb48-16"><a href="simple-linear-regression.html#cb48-16" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Weight&quot;</span>, </span>
<span id="cb48-17"><a href="simple-linear-regression.html#cb48-17" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;mpg&quot;</span></span>
<span id="cb48-18"><a href="simple-linear-regression.html#cb48-18" tabindex="-1"></a>    ) <span class="sc">+</span> </span>
<span id="cb48-19"><a href="simple-linear-regression.html#cb48-19" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
</div>
<div id="hands-on-exercise-3" class="section level2 hasAnchor" number="5.6">
<h2><span class="header-section-number">5.6</span> <span style="color: green;"><strong>Hands-On Exercise</strong></span><a href="simple-linear-regression.html#hands-on-exercise-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this exercise, you are required to download the boston housing data set from <a href="https://www.kaggle.com/datasets/fedesoriano/the-boston-houseprice-data">here</a> and answer the following questions.</p>
<ol style="list-style-type: lower-roman">
<li>Write the simple linear regression equation in form of <span class="math inline">\(y=mx + b\)</span>.</li>
<li>Import the data and fit the linear regression model using the <code>lm</code> function to find the relationship between the average number of rooms(<code>RM</code>) and the housing price(<code>MEDV</code>). <code>MEDV</code> is the target variable while <code>RM</code> is the independent variable. Generate the summary of the model</li>
<li>Create a scatter plot; x = <code>RM</code> and y = <code>MEDV</code>.</li>
<li>Add a regression line to the scatter plot.</li>
<li>Use the <code>confint()</code> function to find the coefficients at 2.5% and 97.5 confidence intervals.</li>
</ol>
<hr />
<p><span style="color: brown;"><strong>Solution</strong></span></p>
<ul>
<li>Load the data and libraries</li>
</ul>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="simple-linear-regression.html#cb50-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb50-2"><a href="simple-linear-regression.html#cb50-2" tabindex="-1"></a></span>
<span id="cb50-3"><a href="simple-linear-regression.html#cb50-3" tabindex="-1"></a><span class="co"># Import the data </span></span>
<span id="cb50-4"><a href="simple-linear-regression.html#cb50-4" tabindex="-1"></a>boston_housing_df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/boston_housing.csv&quot;</span>)</span></code></pre></div>
<ol style="list-style-type: lower-roman">
<li><p>Write the simple linear regression equation.
<span class="math display">\[MEDV = Coefficient * RM + Intercept\]</span></p></li>
<li><p>Import the data and fit the linear regression model using the <code>lm</code> function to find the relationship between the average number of rooms(<code>RM</code>) and the housing price(<code>MEDV</code>). <code>MEDV</code> is the target variable while <code>RM</code> is the independent variable. Generate the summary of the model.</p></li>
</ol>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="simple-linear-regression.html#cb51-1" tabindex="-1"></a>rm <span class="ot">&lt;-</span> boston_housing_df<span class="sc">$</span>RM</span>
<span id="cb51-2"><a href="simple-linear-regression.html#cb51-2" tabindex="-1"></a>medv <span class="ot">&lt;-</span> boston_housing_df<span class="sc">$</span>MEDV</span>
<span id="cb51-3"><a href="simple-linear-regression.html#cb51-3" tabindex="-1"></a></span>
<span id="cb51-4"><a href="simple-linear-regression.html#cb51-4" tabindex="-1"></a><span class="co"># Fit a linear regression model</span></span>
<span id="cb51-5"><a href="simple-linear-regression.html#cb51-5" tabindex="-1"></a>model_3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(medv <span class="sc">~</span> rm)</span>
<span id="cb51-6"><a href="simple-linear-regression.html#cb51-6" tabindex="-1"></a></span>
<span id="cb51-7"><a href="simple-linear-regression.html#cb51-7" tabindex="-1"></a><span class="co"># Summary of the model</span></span>
<span id="cb51-8"><a href="simple-linear-regression.html#cb51-8" tabindex="-1"></a><span class="fu">summary</span>(model_3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = medv ~ rm)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -23.346  -2.547   0.090   2.986  39.433 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -34.671      2.650  -13.08   &lt;2e-16 ***
## rm             9.102      0.419   21.72   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.616 on 504 degrees of freedom
## Multiple R-squared:  0.4835, Adjusted R-squared:  0.4825 
## F-statistic: 471.8 on 1 and 504 DF,  p-value: &lt; 2.2e-16</code></pre>
<ol start="2" style="list-style-type: lower-roman">
<li>Create a scatter plot; x = <code>RM</code> and y = <code>MEDV</code>.</li>
</ol>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="simple-linear-regression.html#cb53-1" tabindex="-1"></a><span class="co"># Scatter plot of number of rooms and price</span></span>
<span id="cb53-2"><a href="simple-linear-regression.html#cb53-2" tabindex="-1"></a><span class="fu">plot</span>(rm, medv,</span>
<span id="cb53-3"><a href="simple-linear-regression.html#cb53-3" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Price vs Number of rooms&quot;</span>, </span>
<span id="cb53-4"><a href="simple-linear-regression.html#cb53-4" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Number of rooms&quot;</span>,</span>
<span id="cb53-5"><a href="simple-linear-regression.html#cb53-5" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Price&quot;</span>,<span class="at">pch=</span><span class="dv">19</span>,</span>
<span id="cb53-6"><a href="simple-linear-regression.html#cb53-6" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">&quot;blue&quot;</span></span>
<span id="cb53-7"><a href="simple-linear-regression.html#cb53-7" tabindex="-1"></a>       )</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<ol start="3" style="list-style-type: lower-roman">
<li>Add a regression line to the scatter plot.</li>
</ol>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="simple-linear-regression.html#cb54-1" tabindex="-1"></a><span class="co"># Scatter plot of number of rooms and price</span></span>
<span id="cb54-2"><a href="simple-linear-regression.html#cb54-2" tabindex="-1"></a><span class="fu">plot</span>(rm, medv,</span>
<span id="cb54-3"><a href="simple-linear-regression.html#cb54-3" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Price vs Number of rooms&quot;</span>, </span>
<span id="cb54-4"><a href="simple-linear-regression.html#cb54-4" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Number of rooms&quot;</span>,</span>
<span id="cb54-5"><a href="simple-linear-regression.html#cb54-5" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Price&quot;</span>,<span class="at">pch=</span><span class="dv">19</span>,</span>
<span id="cb54-6"><a href="simple-linear-regression.html#cb54-6" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">&quot;blue&quot;</span></span>
<span id="cb54-7"><a href="simple-linear-regression.html#cb54-7" tabindex="-1"></a>       )</span>
<span id="cb54-8"><a href="simple-linear-regression.html#cb54-8" tabindex="-1"></a></span>
<span id="cb54-9"><a href="simple-linear-regression.html#cb54-9" tabindex="-1"></a><span class="co"># Add a regression line </span></span>
<span id="cb54-10"><a href="simple-linear-regression.html#cb54-10" tabindex="-1"></a><span class="fu">abline</span>(model_3, <span class="at">col=</span><span class="st">&quot;red&quot;</span>, <span class="at">lwd=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<ol start="4" style="list-style-type: lower-roman">
<li>Use the <code>confint()</code> function to find the coefficients at 2.5% and 97.5 confidence intervals at rewrite the equations with values at each confidence interval.</li>
</ol>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="simple-linear-regression.html#cb55-1" tabindex="-1"></a><span class="fu">confint</span>(model_3)</span></code></pre></div>
<pre><code>##                  2.5 %     97.5 %
## (Intercept) -39.876641 -29.464601
## rm            8.278855   9.925363</code></pre>
<ul>
<li>At 2.5% confidence interval, the equation is <span class="math display">\[MEDV = 8.279 * RM - 39.877\]</span></li>
<li>At 97.5 confidence level, the equation is <span class="math display">\[MEDV = 9.925 * RM - 29.465\]</span></li>
</ul>
<p><span style="color: brown;"><strong>________________________________________________________________________________</strong></span></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="general-statistics.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="reproducibility-and-report-with-r-markdown.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/balsaedi/RCourse/edit/main/05-simple_linear_regression.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/balsaedi/RCourse/blob/main/05-simple_linear_regression.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
